<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?mso-application progid="Word.Document"?>
<pkg:package xmlns:pkg="http://schemas.microsoft.com/office/2006/xmlPackage"><pkg:part pkg:name="/_rels/.rels" pkg:contentType="application/vnd.openxmlformats-package.relationships+xml" pkg:padding="512"><pkg:xmlData><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships></pkg:xmlData></pkg:part><pkg:part pkg:name="/word/_rels/document.xml.rels" pkg:contentType="application/vnd.openxmlformats-package.relationships+xml" pkg:padding="256"><pkg:xmlData><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId8" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="theme/theme1.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/webSettings" Target="webSettings.xml"/><Relationship Id="rId7" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/fontTable" Target="fontTable.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/settings" Target="settings.xml"/><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/><Relationship Id="rId6" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/image1.jpeg"/><Relationship Id="rId5" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/endnotes" Target="endnotes.xml"/><Relationship Id="rId4" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footnotes" Target="footnotes.xml"/></Relationships></pkg:xmlData></pkg:part><pkg:part pkg:name="/word/document.xml" pkg:contentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"><pkg:xmlData><w:document xmlns:ve="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml"><w:body><w:p w:rsidR="008D401F" w:rsidRDefault="008D401F" w:rsidP="008D401F"><w:pPr><w:rPr><w:b/><w:sz w:val="32"/><w:szCs w:val="32"/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:hint="eastAsia"/><w:b/><w:sz w:val="32"/><w:szCs w:val="32"/></w:rPr><w:t>一</w:t></w:r><w:r><w:rPr><w:b/><w:sz w:val="32"/><w:szCs w:val="32"/></w:rPr><w:t>FreeMarker</w:t></w:r><w:r><w:rPr><w:rFonts w:hint="eastAsia"/><w:b/><w:sz w:val="32"/><w:szCs w:val="32"/></w:rPr><w:t>表格处理</w:t></w:r></w:p><w:tbl><w:tblPr><w:tblStyle w:val="a5"/><w:tblW w:w="0" w:type="auto"/><w:tblInd w:w="0" w:type="dxa"/><w:tblLook w:val="04A0"/></w:tblPr><w:tblGrid><w:gridCol w:w="2130"/><w:gridCol w:w="2130"/><w:gridCol w:w="2131"/><w:gridCol w:w="2131"/></w:tblGrid>
			<w:tr w:rsidR="008D401F" w:rsidTr="008D401F"><w:tc><w:tcPr><w:tcW w:w="2130" w:type="dxa"/><w:tcBorders><w:top w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:left w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:bottom w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:right w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/></w:tcBorders><w:hideMark/></w:tcPr><w:p w:rsidR="008D401F" w:rsidRDefault="008D401F"><w:pPr><w:jc w:val="center"/><w:rPr><w:rFonts w:eastAsiaTheme="minorEastAsia"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii="宋体" w:eastAsia="宋体" w:hAnsi="宋体" w:cs="宋体" w:hint="eastAsia"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr>	
				<w:t>用户ID</w:t></w:r><w:r><w:rPr><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr><w:t>ID</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="2130" w:type="dxa"/><w:tcBorders><w:top w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:left w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:bottom w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:right w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/></w:tcBorders><w:hideMark/></w:tcPr><w:p w:rsidR="008D401F" w:rsidRDefault="008D401F"><w:pPr><w:jc w:val="center"/><w:rPr><w:rFonts w:eastAsiaTheme="minorEastAsia"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii="宋体" w:eastAsia="宋体" w:hAnsi="宋体" w:cs="宋体" w:hint="eastAsia"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr>
				<w:t>姓名</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="2131" w:type="dxa"/><w:tcBorders><w:top w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:left w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:bottom w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:right w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/></w:tcBorders><w:hideMark/></w:tcPr><w:p w:rsidR="008D401F" w:rsidRDefault="008D401F"><w:pPr><w:jc w:val="center"/><w:rPr><w:rFonts w:eastAsiaTheme="minorEastAsia"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii="宋体" w:eastAsia="宋体" w:hAnsi="宋体" w:cs="宋体" w:hint="eastAsia"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr>
				<w:t>性别</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="2131" w:type="dxa"/><w:tcBorders><w:top w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:left w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:bottom w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:right w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/></w:tcBorders><w:hideMark/></w:tcPr><w:p w:rsidR="008D401F" w:rsidRDefault="008D401F"><w:pPr><w:jc w:val="center"/><w:rPr><w:rFonts w:eastAsiaTheme="minorEastAsia"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii="宋体" w:eastAsia="宋体" w:hAnsi="宋体" w:cs="宋体" w:hint="eastAsia"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr>
				<w:t>年龄</w:t></w:r></w:p></w:tc>
		</w:tr>
		<#list studentList?sort_by("age")?reverse as student>
			<w:tr w:rsidR="008D401F" w:rsidTr="008D401F"><w:tc><w:tcPr><w:tcW w:w="2130" w:type="dxa"/><w:tcBorders><w:top w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:left w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:bottom w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:right w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/></w:tcBorders><w:hideMark/></w:tcPr><w:p w:rsidR="008D401F" w:rsidRDefault="008D401F"><w:pPr><w:jc w:val="center"/><w:rPr><w:rFonts w:eastAsiaTheme="minorEastAsia"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:asciiTheme="minorEastAsia" w:eastAsiaTheme="minorEastAsia" w:hAnsiTheme="minorEastAsia" w:hint="eastAsia"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr>
				<w:t>${student.id}</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="2130" w:type="dxa"/><w:tcBorders><w:top w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:left w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:bottom w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:right w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/></w:tcBorders><w:hideMark/></w:tcPr><w:p w:rsidR="008D401F" w:rsidRDefault="008D401F"><w:pPr><w:jc w:val="center"/><w:rPr><w:rFonts w:eastAsiaTheme="minorEastAsia"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii="宋体" w:eastAsia="宋体" w:hAnsi="宋体" w:cs="宋体" w:hint="eastAsia"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr>
				<w:t>${student.name}</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="2131" w:type="dxa"/><w:tcBorders><w:top w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:left w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:bottom w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:right w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/></w:tcBorders><w:hideMark/></w:tcPr><w:p w:rsidR="008D401F" w:rsidRDefault="008D401F"><w:pPr><w:jc w:val="center"/><w:rPr><w:rFonts w:eastAsiaTheme="minorEastAsia"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:ascii="宋体" w:eastAsia="宋体" w:hAnsi="宋体" w:cs="宋体" w:hint="eastAsia"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr>
				<w:t>${student.sex}</w:t></w:r></w:p></w:tc><w:tc><w:tcPr><w:tcW w:w="2131" w:type="dxa"/><w:tcBorders><w:top w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:left w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:bottom w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:right w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/></w:tcBorders><w:hideMark/></w:tcPr><w:p w:rsidR="008D401F" w:rsidRPr="008D401F" w:rsidRDefault="008D401F"><w:pPr><w:jc w:val="center"/><w:rPr><w:rFonts w:eastAsiaTheme="minorEastAsia" w:hint="eastAsia"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:eastAsiaTheme="minorEastAsia" w:hint="eastAsia"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr>
				<w:t>${student.age}</w:t></w:r></w:p></w:tc>
			</w:tr>
		</#list>
		</w:tbl><w:p w:rsidR="00A14B3E" w:rsidRDefault="00A14B3E" w:rsidP="00A14B3E"><w:pPr><w:rPr><w:rFonts w:hint="eastAsia"/><w:b/><w:sz w:val="32"/><w:szCs w:val="32"/></w:rPr></w:pPr><w:r><w:rPr><w:rFonts w:hint="eastAsia"/><w:b/><w:sz w:val="32"/><w:szCs w:val="32"/></w:rPr><w:t>一</w:t></w:r><w:r><w:rPr><w:b/><w:sz w:val="32"/><w:szCs w:val="32"/></w:rPr><w:t>FreeMarker</w:t></w:r><w:r><w:rPr><w:rFonts w:hint="eastAsia"/><w:b/><w:sz w:val="32"/><w:szCs w:val="32"/></w:rPr><w:t>图片处理</w:t></w:r></w:p><w:p w:rsidR="00490FD6" w:rsidRPr="00490FD6" w:rsidRDefault="00490FD6" w:rsidP="00490FD6"><w:pPr><w:rPr><w:rFonts w:ascii="宋体" w:eastAsia="宋体" w:hAnsi="宋体" w:cs="宋体"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr></w:pPr><w:r w:rsidRPr="00490FD6"><w:rPr><w:rFonts w:ascii="宋体" w:eastAsia="宋体" w:hAnsi="宋体" w:cs="宋体" w:hint="eastAsia"/><w:sz w:val="24"/><w:szCs w:val="24"/></w:rPr><w:t>以下是一张图片</w:t></w:r></w:p><w:p w:rsidR="008D401F" w:rsidRDefault="003B578C" w:rsidP="008D401F"><w:pPr><w:rPr><w:b/><w:sz w:val="32"/><w:szCs w:val="32"/></w:rPr></w:pPr><w:r><w:rPr><w:b/><w:noProof/><w:sz w:val="32"/><w:szCs w:val="32"/></w:rPr><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0"><wp:extent cx="2888525" cy="2238375"/><wp:effectExtent l="19050" t="0" r="7075" b="0"/><wp:docPr id="1" name="图片 0" descr="微信图片_20181224150420.jpg"/><wp:cNvGraphicFramePr><a:graphicFrameLocks noChangeAspect="1" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"/></wp:cNvGraphicFramePr><a:graphic xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:nvPicPr><pic:cNvPr id="0" name="微信图片_20181224150420.jpg"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="rId6"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="2888525" cy="2238375"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p><w:p w:rsidR="009C09D5" w:rsidRDefault="009C09D5"/><w:sectPr w:rsidR="009C09D5"><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1440" w:right="1800" w:bottom="1440" w:left="1800" w:header="851" w:footer="992" w:gutter="0"/><w:cols w:space="425"/><w:docGrid w:type="lines" w:linePitch="312"/></w:sectPr></w:body></w:document></pkg:xmlData></pkg:part><pkg:part pkg:name="/word/footnotes.xml" pkg:contentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footnotes+xml"><pkg:xmlData><w:footnotes xmlns:ve="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml"><w:footnote w:type="separator" w:id="0"><w:p w:rsidR="009C09D5" w:rsidRDefault="009C09D5" w:rsidP="008D401F"><w:r><w:separator/></w:r></w:p></w:footnote><w:footnote w:type="continuationSeparator" w:id="1"><w:p w:rsidR="009C09D5" w:rsidRDefault="009C09D5" w:rsidP="008D401F"><w:r><w:continuationSeparator/></w:r></w:p></w:footnote></w:footnotes></pkg:xmlData></pkg:part><pkg:part pkg:name="/word/endnotes.xml" pkg:contentType="application/vnd.openxmlformats-officedocument.wordprocessingml.endnotes+xml"><pkg:xmlData><w:endnotes xmlns:ve="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:wne="http://schemas.microsoft.com/office/word/2006/wordml"><w:endnote w:type="separator" w:id="0"><w:p w:rsidR="009C09D5" w:rsidRDefault="009C09D5" w:rsidP="008D401F"><w:r><w:separator/></w:r></w:p></w:endnote><w:endnote w:type="continuationSeparator" w:id="1"><w:p w:rsidR="009C09D5" w:rsidRDefault="009C09D5" w:rsidP="008D401F"><w:r><w:continuationSeparator/></w:r></w:p></w:endnote></w:endnotes></pkg:xmlData></pkg:part><pkg:part pkg:name="/word/theme/theme1.xml" pkg:contentType="application/vnd.openxmlformats-officedocument.theme+xml"><pkg:xmlData><a:theme name="Office 主题" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><a:themeElements><a:clrScheme name="Office"><a:dk1><a:sysClr val="windowText" lastClr="000000"/></a:dk1><a:lt1><a:sysClr val="window" lastClr="FFFFFF"/></a:lt1><a:dk2><a:srgbClr val="1F497D"/></a:dk2><a:lt2><a:srgbClr val="EEECE1"/></a:lt2><a:accent1><a:srgbClr val="4F81BD"/></a:accent1><a:accent2><a:srgbClr val="C0504D"/></a:accent2><a:accent3><a:srgbClr val="9BBB59"/></a:accent3><a:accent4><a:srgbClr val="8064A2"/></a:accent4><a:accent5><a:srgbClr val="4BACC6"/></a:accent5><a:accent6><a:srgbClr val="F79646"/></a:accent6><a:hlink><a:srgbClr val="0000FF"/></a:hlink><a:folHlink><a:srgbClr val="800080"/></a:folHlink></a:clrScheme><a:fontScheme name="Office"><a:majorFont><a:latin typeface="Cambria"/><a:ea typeface=""/><a:cs typeface=""/><a:font script="Jpan" typeface="ＭＳ ゴシック"/><a:font script="Hang" typeface="맑은 고딕"/><a:font script="Hans" typeface="宋体"/><a:font script="Hant" typeface="新細明體"/><a:font script="Arab" typeface="Times New Roman"/><a:font script="Hebr" typeface="Times New Roman"/><a:font script="Thai" typeface="Angsana New"/><a:font script="Ethi" typeface="Nyala"/><a:font script="Beng" typeface="Vrinda"/><a:font script="Gujr" typeface="Shruti"/><a:font script="Khmr" typeface="MoolBoran"/><a:font script="Knda" typeface="Tunga"/><a:font script="Guru" typeface="Raavi"/><a:font script="Cans" typeface="Euphemia"/><a:font script="Cher" typeface="Plantagenet Cherokee"/><a:font script="Yiii" typeface="Microsoft Yi Baiti"/><a:font script="Tibt" typeface="Microsoft Himalaya"/><a:font script="Thaa" typeface="MV Boli"/><a:font script="Deva" typeface="Mangal"/><a:font script="Telu" typeface="Gautami"/><a:font script="Taml" typeface="Latha"/><a:font script="Syrc" typeface="Estrangelo Edessa"/><a:font script="Orya" typeface="Kalinga"/><a:font script="Mlym" typeface="Kartika"/><a:font script="Laoo" typeface="DokChampa"/><a:font script="Sinh" typeface="Iskoola Pota"/><a:font script="Mong" typeface="Mongolian Baiti"/><a:font script="Viet" typeface="Times New Roman"/><a:font script="Uigh" typeface="Microsoft Uighur"/></a:majorFont><a:minorFont><a:latin typeface="Calibri"/><a:ea typeface=""/><a:cs typeface=""/><a:font script="Jpan" typeface="ＭＳ 明朝"/><a:font script="Hang" typeface="맑은 고딕"/><a:font script="Hans" typeface="宋体"/><a:font script="Hant" typeface="新細明體"/><a:font script="Arab" typeface="Arial"/><a:font script="Hebr" typeface="Arial"/><a:font script="Thai" typeface="Cordia New"/><a:font script="Ethi" typeface="Nyala"/><a:font script="Beng" typeface="Vrinda"/><a:font script="Gujr" typeface="Shruti"/><a:font script="Khmr" typeface="DaunPenh"/><a:font script="Knda" typeface="Tunga"/><a:font script="Guru" typeface="Raavi"/><a:font script="Cans" typeface="Euphemia"/><a:font script="Cher" typeface="Plantagenet Cherokee"/><a:font script="Yiii" typeface="Microsoft Yi Baiti"/><a:font script="Tibt" typeface="Microsoft Himalaya"/><a:font script="Thaa" typeface="MV Boli"/><a:font script="Deva" typeface="Mangal"/><a:font script="Telu" typeface="Gautami"/><a:font script="Taml" typeface="Latha"/><a:font script="Syrc" typeface="Estrangelo Edessa"/><a:font script="Orya" typeface="Kalinga"/><a:font script="Mlym" typeface="Kartika"/><a:font script="Laoo" typeface="DokChampa"/><a:font script="Sinh" typeface="Iskoola Pota"/><a:font script="Mong" typeface="Mongolian Baiti"/><a:font script="Viet" typeface="Arial"/><a:font script="Uigh" typeface="Microsoft Uighur"/></a:minorFont></a:fontScheme><a:fmtScheme name="Office"><a:fillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:gradFill rotWithShape="1"><a:gsLst><a:gs pos="0"><a:schemeClr val="phClr"><a:tint val="50000"/><a:satMod val="300000"/></a:schemeClr></a:gs><a:gs pos="35000"><a:schemeClr val="phClr"><a:tint val="37000"/><a:satMod val="300000"/></a:schemeClr></a:gs><a:gs pos="100000"><a:schemeClr val="phClr"><a:tint val="15000"/><a:satMod val="350000"/></a:schemeClr></a:gs></a:gsLst><a:lin ang="16200000" scaled="1"/></a:gradFill><a:gradFill rotWithShape="1"><a:gsLst><a:gs pos="0"><a:schemeClr val="phClr"><a:shade val="51000"/><a:satMod val="130000"/></a:schemeClr></a:gs><a:gs pos="80000"><a:schemeClr val="phClr"><a:shade val="93000"/><a:satMod val="130000"/></a:schemeClr></a:gs><a:gs pos="100000"><a:schemeClr val="phClr"><a:shade val="94000"/><a:satMod val="135000"/></a:schemeClr></a:gs></a:gsLst><a:lin ang="16200000" scaled="0"/></a:gradFill></a:fillStyleLst><a:lnStyleLst><a:ln w="9525" cap="flat" cmpd="sng" algn="ctr"><a:solidFill><a:schemeClr val="phClr"><a:shade val="95000"/><a:satMod val="105000"/></a:schemeClr></a:solidFill><a:prstDash val="solid"/></a:ln><a:ln w="25400" cap="flat" cmpd="sng" algn="ctr"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:prstDash val="solid"/></a:ln><a:ln w="38100" cap="flat" cmpd="sng" algn="ctr"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:prstDash val="solid"/></a:ln></a:lnStyleLst><a:effectStyleLst><a:effectStyle><a:effectLst><a:outerShdw blurRad="40000" dist="20000" dir="5400000" rotWithShape="0"><a:srgbClr val="000000"><a:alpha val="38000"/></a:srgbClr></a:outerShdw></a:effectLst></a:effectStyle><a:effectStyle><a:effectLst><a:outerShdw blurRad="40000" dist="23000" dir="5400000" rotWithShape="0"><a:srgbClr val="000000"><a:alpha val="35000"/></a:srgbClr></a:outerShdw></a:effectLst></a:effectStyle><a:effectStyle><a:effectLst><a:outerShdw blurRad="40000" dist="23000" dir="5400000" rotWithShape="0"><a:srgbClr val="000000"><a:alpha val="35000"/></a:srgbClr></a:outerShdw></a:effectLst><a:scene3d><a:camera prst="orthographicFront"><a:rot lat="0" lon="0" rev="0"/></a:camera><a:lightRig rig="threePt" dir="t"><a:rot lat="0" lon="0" rev="1200000"/></a:lightRig></a:scene3d><a:sp3d><a:bevelT w="63500" h="25400"/></a:sp3d></a:effectStyle></a:effectStyleLst><a:bgFillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill><a:gradFill rotWithShape="1"><a:gsLst><a:gs pos="0"><a:schemeClr val="phClr"><a:tint val="40000"/><a:satMod val="350000"/></a:schemeClr></a:gs><a:gs pos="40000"><a:schemeClr val="phClr"><a:tint val="45000"/><a:shade val="99000"/><a:satMod val="350000"/></a:schemeClr></a:gs><a:gs pos="100000"><a:schemeClr val="phClr"><a:shade val="20000"/><a:satMod val="255000"/></a:schemeClr></a:gs></a:gsLst><a:path path="circle"><a:fillToRect l="50000" t="-80000" r="50000" b="180000"/></a:path></a:gradFill><a:gradFill rotWithShape="1"><a:gsLst><a:gs pos="0"><a:schemeClr val="phClr"><a:tint val="80000"/><a:satMod val="300000"/></a:schemeClr></a:gs><a:gs pos="100000"><a:schemeClr val="phClr"><a:shade val="30000"/><a:satMod val="200000"/></a:schemeClr></a:gs></a:gsLst><a:path path="circle"><a:fillToRect l="50000" t="50000" r="50000" b="50000"/></a:path></a:gradFill></a:bgFillStyleLst></a:fmtScheme></a:themeElements><a:objectDefaults/><a:extraClrSchemeLst/></a:theme></pkg:xmlData></pkg:part><pkg:part pkg:name="/word/media/image1.jpeg" pkg:contentType="image/jpeg" pkg:compression="store"><pkg:binaryData>/9j/4AAQSkZJRgABAQEAAQABAAD/2wBDAAoHBwgHBgoICAgLCgoLDhgQDg0NDh0VFhEYIx8lJCIf
IiEmKzcvJik0KSEiMEExNDk7Pj4+JS5ESUM8SDc9Pjv/2wBDAQoLCw4NDhwQEBw7KCIoOzs7Ozs7
Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozv/wAARCAKAAoADASIA
AhEBAxEB/8QAGwAAAQUBAQAAAAAAAAAAAAAAAgABAwQFBgf/xAA/EAABBAEDAwMDAgUDAQYGAwAB
AAIDEQQSITEFQVETImEGMnEUgSNCUpGhFTOxwTRictHh8CRDU4Ki8QcWJf/EABkBAQEBAQEBAAAA
AAAAAAAAAAEAAgMEBf/EACMRAQEBAQACAwEAAwADAAAAAAABEQIhMQMSQVEEEyIUMmH/2gAMAwEA
AhEDEQA/APSW8fsiCZo2Tqci7p0klIkbOE1BE3hEUOkkktNEE6YJFAJMiA2SpSMELu6Puhd3VABB
3RqNzbK1VCKSXCSGjHgomITwUTExmi7ISaFpzygc7lKhPe0A2a2WB9RZoLo8Vr77uHx2Ww73O952
4pcf1DLfNmTyahTnkN24C5d3I6/Dx/1o8SUxZoIH3ghV+rZDmgUQdR+3v+6rGR4yGHV/f91BmmVz
9bSR/wBVw6v/AC9c5n21a6LquUvcT/4uR+EWW1sOU+QOA1t787fKi6RK7TLfbgKHqmXA2Rr5j9o2
pc/jrXf/ALU/qfqCWNbIHDe62U4dHBCA54GrZzb3vyPlYE3XZ3/7bBGyxu/Yu+AFltlndkE/qHv1
O1Btdwu08uFdNPkYxc2M09xuiCqgk1EkilUhkaz+E8B09aiB2PwidlMkGkVq7qYtSS5TGh1H7VJB
L6kZceFlzHTQoHdWYZS9m+wUdWdYcfa4fO/CNr4migdR8qn6w0+nDVk7lFG0RA6t3KMXGNYd2uN+
E5dp52VZple3Yhg+O6cM1Hlx+VJI+VrhVn9kAY0f1fuVIMcgUN/yU/6SZ387Wj4pSRhrG8gH8lRv
Md3Yb+CrH+m2Pc8u/elGektJrX/+Skqul39ptAXEjagrp6TWwd/lO3oznbF9qLLeHE/ZqQBg3L2L
YHRpG8FEzpT2fc3UCoMhhiHfT+6mjEf/ANUO+CVpHpLXf/LCik6Ia9jQCrUriEngj4TGAbiRlnyi
d0jKZemRQvxc9gJLgaUj/o4H7E6UE3SInMoNBQ+plMNPZ/8Aijimfdlmn/qpKL+lxtJGkqnJhs1E
f9F0AlD71NFJGHFkFOICk5sY+l1sUnp/zPaWn+pq3T0mKQfw/wDBVGbpskTiC5w8EKGKjWSSsBdU
gHDm/cEbZ8iFwd73BvB8KSFuRE4jW0i+a3Vxr2vbWRFt/UOVBe6b1lzWNfer+q+V0XSuuRZQtj6c
NqK5ODGDXfwZib4bItCF/wCijMsmiOzvpamdYfpK7Nj/ANRI0vdbGN3P9RRZmZFgYsmRO8MYzl3z
4XPdG+oo5pHQ5BDbfsbr8Kv9UZc8+dDFEXfpoqLqGxNrpbk1znPnG5h9Xlz8wwwN0hoDpC+9lssB
A2da5zpmXFjYUksh9WXKdTQByF0UIaGNDG6QBVeFrmeNXfP1SjhO3lMBRKccrU9OJzwnj5KIVW6H
7SmKDSQ/J/ZEkkkkkokkkkpEkkkpBf2QoyLCHQUwGSTuCZMDXb3TpgnXEl2RMArhM3uib3QoRCdq
SSTgqSpIcJKBJJJKRJJJKRjwhd9pRHhMqGI0jwnPJSP2ranoNJtItOELm2UYDEbo0BFbIXyEChuq
KCc67CgnmZD7nki9lJvVqrmMjnjLHO7qp5m0GRMNTe/crjpi6OZ1gNOs7FdMWvieI3uDm9nefhYM
7RKZZXlpZrIF7FcOvL08c2XWfHI5+S3YGgVYkZC/GDadqcd67J8bHhje57QdR/cKXKe6OIyNlETa
7hc8yO/tUhcyGJ38pJol2yozyQzyOOqNzuB3VbqMrpWlonLh3s7LLZjv1aYctjXE1Y7K45k9ufVb
WD0fCyXSv6kXPEYtgHH7/Kyup5ghJi6biDHbxrf93+eLVnG6bmwsL5Ooa+9J5TjSHRM4ahsfldcn
45Xy5yGWUT+oXlrg668HutCZ7nETA0SBbQjyOl44cXsceeLTxQtNN/5WcGGaPWAPccqQimU0Ek7b
KX0BG4N5vv4VqOJzI/YRf4U1itBF6UZc9p1ngKzDiOkOqX2t7WUmRODy99vPhA79VPIWtG18IOL0
cMNgOcKCsDFZI32vACoQYeSDRaD5WnFjua23EA+FQyGZ01t/cVPH05vdxKeFoaaDif3VqK74/dKV
/wBAwD7SojgNN+0rUjsmjwp2wtP3BCYrMFgH2bpHCrs4Lc9CM3TSgdA4cNVEx24rh/Ui9A/K1DG4
cs/wo3+3+QpTPbjPcLaaQnFyG8EFXDM4cQ2o3TS//QQlURzD+QEpvR7vi/spnZUw4i0/JQjLdW4B
UkL8NsooNH7qB/TowSCxqufrR/QnbO1++kX8qTKPRtRcWuFKKTpDgNNXfhbRlBH2/wBlC/WdwUph
HCy8cn0rd8FJs7705GOfzWy2NcjfubYQOyQL1RWPkITNOPBOPsr5aonYLm7RvD/grU9PFfZFRuPy
hONsSN/BCgz2tlgNujB+R2RtySAQ5mofKn9OQA3uB2UEkTXAggt/CiKN8Ej9UmKYnN4cArWMBE9r
TIJ8c/eHHdotZhheDTJGn8qRkzo7ZNBXy3upOp6JgQSPbM5wDGe1jO66NtbgELz/AKZ1cxPLA8mj
wV1eN1ZrsVkn3E7AA7rrxfDl8m1st37p6vZZ+BPPMCZWhngd1d1EVuujkkB7J6B7IAe55Tgk/hMQ
k9bEpm8/upQKSsRpDkKVJSwLgNJ2QKRKhR2CjiNJEm7KZ0ySSSiakJbXCNRpgbASSTrIOzuiQs7o
1mtQkkklI7eE6ZqdMBJJJJBJJJKRimTlMj8agaTHhO7hD2CofwPdPSbunSyB4rdBSJ5QjYEnhGoM
hDGklUZiZYnlrmtrhHmTOq9Ln/AWFl5GfkS6YYjG0O3DjyuXVdfi5tqD6jzZ8Lprp4iJHg16Tefy
sB2c84DpepkMpwprDySun6liullc4gEuF78BY3UWQTdP0GIyiJ90wbj5XK19D6yQEGYciBrYSGsH
FndRZjgGupznOc29JF0PhUMTFnkcx72uiivbV3/8loTZIDg4vJDdhXCnK9YwBg5GZLpLvTivexuV
pQYMOECGtB/7zgrLc3WC2KPUa32oKs9sk9h7S7f7RwtRyqw7IY+MtNHbaljT9OfkPc6IkA7hamPh
Eut7QB+VcfpijBawEjZOs45uPBljdocHfm1OyNsD9xa1Hkyk+2goDhkkE0QjTzEBkHLWBWcZrntJ
IoVskcZjW7bnwrOKwUCCduypWkLJCHH2jbyjZ1FsYpjbVp8LJDqoNPf5Sjx8Y3QBWbUqu6nMfsZu
lHPlyv3Cln0QyfZfwFEcwsH2EIlWL2O14dqfX7K7FnRRVZb+4XPy573sIY8tPlVmGR1ufI5x/wAJ
hkde3q8A7t/YKQdYgPhcVJnvgsEjb8KIdZle4Bv96SLHeN6tAewUrepQOHC4eLqb9XverTOpt8u/
NqZx1/62GuELsqJ9+xcw3qTRy91Iv9WYPtlv4UsdA6SI9kBlZxoBWCesj5/snb1XV/UsnG3J6Lx7
mKq6GA3QWe7qIreyg/1Fv9LlGRfONGRsEJgq6KqN6j20lSszmD7tvyhDMTgmvsWpjnx9nBCcuM8k
Ba/EMBp7f3TPY0itIKH143GmuRahXIKNWKsuC1/ubsqzY8jGNAkhaYcPIRgteKIv8q1M8ZEbj/Gp
jvKL02SWQQ4eVcdiQPYQQAoG9NLCSx2yYFR+C2W/bfawqz8SbHsseXAeVpiKRl6k5OxD2Ckpksm0
mpsZrj5bsVcx8yKJzXxyOYQeCjONFICW7KP9OW6qId+Qr7YnTdN663Lf6byGu8+VptlLrFhcIwux
3h5bpINggrpunZ8efCJGkse3Zw/6rrx1rl3z+thkp77qRsrSCCaVWJrvU9pDxzypGgb2QD8ro4rL
Xj5Reo1VWxG7BcR8FPp8SFvwQlLQcCnVdrJK9rrCIPcBTioJgU6iElWSia5ru/8AdaiS18JUPCDQ
fIRobMQKOwQI9LfCF/KgYoS2+EVcpUoNYAUnAG+yQCeljThVScJJBURImDlCiZ3WkKvhKvhOksk1
fCVfCdJSNXwlXwnTKQHfcm8p3DdMn8AXcIewRO4KE7gKh/DISU6F7gxpcTQHdLJnVSjcCRtSxOp9
ckhna3E0yt/mBG6lxeuQyt/iAxEDfVuFn7SMfdcna1wIcQAfhU5MdkETpI9T65vlRZWe2c1ES7/w
gqKLqAx5dEkcmh+xFGlw69vX8PWRUz853puG7Dx/4Vm4Abjwvj1EucS7fn8rR6jHGyUiE6hILDv6
fgrJ9GYu9oOomtSw9E7RTBznut+sdms4/dKLprpnapAHVxfZasHTmxi3C73Kn9No2AoDwtMXrVKP
AjaA3sOwCnZ09gBFN0nsAjMsUXdRO6i2NpIb7u26mcEcOJv8otN+mY3bSP3Wp05gngL5GAWo8psU
TzdAX3Rrnvnwy5Im0QGAKq/HaRuL/C1tUbjsAbTnFDh9v+Et6xWwMBsDjyhllaw0wNvytR+ECCNK
qS4Gm9lNSqBL5fvdR+Fq9MwbbZaq8OFrkbt3XRY+OzGx7cRdLFZ6uOe6nj+nkOBFBUTEC2itjqAZ
kSn8qqYG1VIjpxPDKdBG03SCRpc0tj28rQkhFkUofQJump1uRjTRAOp1kqB8Lx9gA+Vtvwi42WqF
2JvsFasYbmOu3Fx/CMTEcf5WnJhnfZCzp4I3DT/yrWMZ/qF9hzirENMAI3V7/TI2ssRj+6B0TYxs
0V8LcqwDHFx2AAU7HEdwfwoBI4bNa390xyJWitACyyuskA3Lf7hF+oZvtX4Co/rDVO/woXZukmg4
/NKMX5MgdiQg9fyb/KqxytlG7iE7mhm4/wAqS2JGHwkQT2VIzgE0QnGS7+pSWi11+00UJdktJDCV
CMojsCjZmRk09pA/Khp/1mXHYNH9lcwsiaUW4Uq8MEeQ8mNxH4K02QelF/5rnep6ZtVZs0xvItFF
1OxWpUcmGX1HGg4HwVUkjmYfaz+5XTm+FG6M6+6lZLDI2nOolc4MzJiIDoxX5UjM2R4PY9lrGm63
GGq4pAQeyMwnxZWF+syYhbXXfNKaDrske0rdvJUGqcRsgNHfwU+NLP06bW2tJ2dSix+rxSngC/Cu
CSOZp/srm4Ov+o1Icl0g9RsYI/7p/KvQ5zZG7kvrsQsHGkOI6mEOH5V6HMhmouFEdl2nTjeMbMUs
U20bqd48Ii2r1Cx5WaGwkBwc4E8FpUrXzM2bLq+HLesLwj7tJH7pnNoe7lVv1hZvpJHBUwymObTg
QeUsnaLBrmxZ8/jwpPbe/KAObezr27J2h3L+a3pJSh1BJvNeU1b0n0pSRCQCEtSVqw6HQfIS0HyF
Ikg40m3vaJIpBY9ggkkAiaObWvSJg2tEknQTBIJwnQjFJJKlREkmTqRqB7IDsVIo3clMATwUycpk
GAKE0QQVIRsUDhQKmWX1DpkMzXysYGvaLNLnfXgdYBAING11mU/RE7fkUuHzsV0GU8O2JNgBcu/H
ljGjDO6GUmJ4LaquytHPMzA3QxpH9XdZuFE5sQe013Kt2MinGPdvcLD0cejHaw/d/wAcIoxGDuwB
M0+oXuIqkOpjGudIaa0Wp2SyuaGk6h/dUpZSI3FpFj5We/IOVK59aY28C1FHkPkkNEOHzwFJMQdQ
e5wN8BTQ4rnEF41OPHwosQSZU1CnBh3obLdhjjiFuIv/AIWOmer4WsdnoYjWeBusjPxpeo5lk6Im
9weVdyMieYGPEYHOPnsmg6c8NvMyGtHgHZXLHPN9o4I8fGiALgAO/lWW5MLxTLP/AIRaNg6bGKMj
HV2tDN1GPFjccbC9UDuEtn9Rvg/2UMrGPbws6br+RNdYYZfYlBD1Cd76dFpCNXn8aLY9FU1PMyWb
ayAghle4XambI5WNSf1DH01ziSU7+luI2VgTyjYEbIxkTf1BWNTwzz0hx5S/0ggf+i0m5Mtdv7Jn
ZEu+4/srGvtWc7pTiKH/AAov9Ge3ta0TkzDv/hP+vlaNwCgbWYelU2nMVZ/SWX9pC2v9U0/dEhPV
cWRtOjI/ZMW1hHpTgdrpAejk8MW83JxS73OpvlTtmwnbetsleXITYGgn2bhVJsVwG7DXkFd4cDGm
bbS1191Xn6JE9hDW7qxSx587HLXWBajfjh29Efgrs5+gFoJDARaoSdM0kj0v7LNuKWOY9F0Z/wBx
3ncoxO4+wgH5W9J00OFGMj5VY9E7tWb2sn9ZrMUTu9rdvhPk4DsdheLoLo8DpQibZ/4VfqzY9DmN
G5+Efdj9cc/M0vLd0eKZcqQBlndaLunxyHjc/C1+mdPgxI9bqCb34V9eEvSunnDh9STuFn9a622P
+Gx3CLrPV3GIxYzhR22XIzwzPkc51krHHO3axJf1qjqTzvrpS/rXmqdeywWtlG26sxF7eTsu+43G
vHnxkkSH/ClaYpN43NKzWBkjCK3/AOVIzGfCNbXHSeytLQB0Hi0TQ127q/BVSPKL/b2+VNr2OyYl
gANNtb/ZWsbJfCSH7sf3HZZrM4MaQWFTwZjJDQSG/hR+sHO9T8Edk2RDPETTS4eQqfT8gtmLQ6mn
ldBi4Zyz/ugCuFvlm/8A1jx9TnidpsPaP5XK7D1csrWz2+AreT9LskBImAcVm/8A9fyWFwbIHV5W
vMYsl9NiDquNLC4CQNJ7EqaHJja0ucQfwuUmZkY4/iQbcEhFHM91Mje4HmrTOheI7GD05pBK11UK
2PJVhoO+9/uuUx58rFaAQSAb3Whj9bIkYyZhZ8+V0ljH1b4fQoo2m7VJubE9mpsg44ViF7nN1GhY
7KCU7JDndI7i0gOVayKkx4TWUqKE1wkknTGjs7pzyhBpLclSH3SpMAiHCyPZAbJ2pwNkkIimTlMq
GElQSTJJEbbKMhSC0Dq3NqlZBSE7FV257HTOjJqjyrF7WEatCSebUcsjWNLnbAJsjIZCy3u0rDyu
qDIkLXAsY3sOSq9xJjP+tndpJEcfN91ldXhiMolBDn1XKnmyZHR6Y4/TjPfuVC2EWHaga51Lj11s
a55R9PYXRuZze5KnI/Tt0Vynja2Gy59/A4U8jo/QEhFn/lZjrIq6dLC3eysvOyb040fB+4q/mZQx
4iTvYOo+AsY5BefUI0tIFH4U2r5jnYsLowaeTVeVDhYkuVKI4yWsB97j/wBEHrZPUpnMxYS8vdsQ
Lr5JXUYOHB0vCEmXkN9v8o7lHlLHT8H0ohFDGQDy4q1M7EwWEPuaT+kKk/quXm3HDH+ng/r/AJj+
yjfoxyARrceN9yoSIn5WXI94gYIGvIsoG4D5nF0uQ6Q9wXUArccEsz7fTR4V3HxaG4CsaxRx+msZ
uN1bZAWNNCweQrrIQBwi0jsFSCsqXCjcC5rA13ilCIdB9zVsPjFWAofSDmm2rGZROsUmAVsFIwlG
IqKJsa3G5TNFp9PypGxlF6YSkbWJyzalIGgCgE+nbhCVjGL5QOiCt6QUBZasalUZYW0oDA3ytIxj
ilVmhAvShqVRmx9va5QaXt2CvuhJFqMxHyEbjXtEzJcwaST+ymj606IadZ/JUEkdHhQPjvsj7Vi8
tB3X5WbPjbI34TxZ+Pk7kAHws0Q/sqssL43W00Vx76srl1y6IwxuFhthZ2U8xSFrYxXlV8PqEkOz
i791pR5UWY3S7TfG63M6miRlyZUtGvas+V7nuJcSStbMxDETtYWe9oBJq/hZx15yqeuOMlzydvCq
ZPUJS4saaCuTte8kCOm9lnywuJcS2iEw4qukOonZISMP3D/Ccx87JhADyStyinAhdw3/AAhdDjkE
734ClbDQoA0hc+KM78rWso2QxcgkHjhXcfHAAAl1D5VRvU4ozwf7KZnW4uzf8Jg1Zk6X63ujFH4Q
/oJowe6UX1AGH2gfuruP1uObljUjVH9K4ggtv9lH/p8jXB0epp8Ldjy8UmiKJUvr44oOdR80k6x8
QzMn0vaQD/N2K676byA/2PO5CyTjwyAOa8V8FWOluGJkNc19m6srpxfLn35jri0EX2UM0DHnW29Y
RQ5bHCjVfKnJjcw1zXldfbl6cx1AtLzG2iS/YEqSLpWPkEkn03AEmlUzJfWzJWtjsxO2rstTEY8Y
oe8g77UsyHbFQ4suPK2MnWPk2r78JmQC18Qa0bWp4WCS2ubZ1W74+Fac3s0crWL7MR+FL01wkhdq
bdkO8LSxckSMBDt+4Ur8cSAtfRJFFVB092I4yRPJvzwlm1pMmbwbBUuqt7VTHnbIAJG0VO0lpDbs
HuplYSr4Tc2OKSdwktVJJJU9Iydt7pAImiwSs21CoJ0wvyluiEQTpmp1A1JUE6SkaglQTpipGdQa
VRnynxk1EXN8q4+yFGRtX/KkxpoRMfViOnfcdwpxlOx4PcC9xGylyMT3F8Zo+B3UFepYqnN5CyEH
6abNdqmcfgDsjOHBiROcQNVbUOVZblR48T3OfvxSyp8yTOkJ4Y3+nwsWNcxScZZi4D3E/wCEGPie
m52qbW938qiblFsxbGeT2Vl9RxGQfc7YfC5ush5G2NPFqHIyNETWgWRsB8qVzmiIOkcLYLtZj3TZ
koZAwvcXbV2S2hz2nNmEbdQjbsSO5UzejNliEmS/0MWPYWacVvQ4mL0fHbkZjtT4xs2uT+FzHV/X
zsszySPIO7IHcNH/AL8q/AJn1Di4xOD0bEaPT+6V2w/byjhxZJZGyZD9RvVXZRYuL6MX2jV/Sey0
sSEMY57v2srMrcSNd6TyD/uEX+AihYHv1NbqPkpoIHSE2bJPPhamPjCNvHK1EGCCmAnYqyxiQZup
Y2eVqQWhDduEtKk0Jwz8qxjUOm+yhkjoq4GgFC5thF5MZ5j3OydrKCnfHRO6HQOxRjcJrdikBsiC
dMiDpTBt2jSaErQaULmjwpqCjcNigyoiz5Ub4xW6l34TFqy1qs6Kga4UDo9JVxzbCicxGHVcwhze
FXfAByFfpM5gPZWLWaYa9wUUsYeKIWg8DcHZVZG7EhZ65nUxWarHEGk1aqODonkjYhXw9wBs9lnT
Sa3uoFcOZZcY4l3G50+QdQxyx59zQsvNw3Y0rtX2+VXw8yTByBI11g8hdJlxN6lhteyjY7LdjN3j
rfxzDS1xaLq+5Rz4PqNtov5AVbJidi5DmEEAeVpdOlcWaSbb5Wb1Y111ZNjnOo4z4DbWn5VAZBFi
16BJhw5LdL2D80sDqn0m4F0kJ58KnTE71zb80sNKpLngOcDHqK0MroWXE0ktJCzThy+oWltfsuvP
UP2RtymzPr0aKnmd6GKXBjdR4vlSCGPFjLn0APIWdI/Iz59McRLOxAWubHO9IxnT76WMv5C0+lyz
vaXPpn7I8ToIgd6uS7gWApciRrxpiFNCuu99DU780A+QOSpP9RkYw6Weo3wVhSZIbIWA2Rz3BVjA
y9OsaQRwQVqa1K3cXPhyPaxpY4EbArSZkMiIEj9LQfuPlc46IECRnDt7b2VzCzJC70pAySI9yN1q
NO96RO2aENJ1uvYrTdK2GN7yLDQTuuM6d1EYJJbuz/IW1ldSld0x8nolzHNppXXmuX18osZhdF6r
m/7pJv4V3Ee4nQftB9opZfTpZZHRY7WEkNF78Bb+Hi+i8FxslbjNWY2VXtq1Z0fCZg3/AApN9wFo
IXxg7GxfdMYDp0h2ofKMA8cqRrdqUFMwU4AchDvHMwE7ONK29tcKFrdcgceygtc7JjwnASpTTUTJ
6SpU9AYFkpDa6SaOU9LJO3e09JmjlEhGTpikLUDpJJKRJjwnTKQSoyL5Uh4QuT+JF+yo5emN9gVf
daBFd1ndVmjbF7h7jws/iZ+VGHMDWuJF7n/ooM4nBwHMBAc8dk+Q6Y6XR7b91k5uQ6Rkhc+zyuNr
fMB07HeNT37OdxavTOL2FoOzR/lRQPPoDsaUkJLnngAD/KI6K+U8FjYyRbq1K5izwdJYGhgdK8cr
n+r5kkcjPRNyOJAHhWMWGRsMZkIdIRubU0v5uQ57w+WRz3ADTXY2oGtI3ddnknkqSBpI9xuu6J4D
ATyQUNSI4oPUm9MH5eR2V18dBrGjbhLAgMcZcRuTdq5jwh7y5wsBWL0LGxhGwWN1bjZvwijZR42U
rW/C1zGbQtYPCMAJyyu4SFjhLNpkkQYmr4UAkJiLRkUmpJlQPjQFlKyRso3N2QZUOn4S0oyNkJCD
KbSkBSdIKJVsgcOVKBtygI5VChc3uE1f3Uh/shIFK9GIiKQEKUhCQsmVA5tbhCCpy1CWqaVZW2VX
ez/KuvZajcwKxaoOircBVZ4Bd1S1XMHdQSQg2sY1KxZsehta1ugZrmfwJCduFHJjgBQBhik1t2IW
bB8kncxb+o8BskBnj78rnsTLdjzBhPt+V15e3KwCCP5Vx/Ucf05jXZYv8cPit6l5rWk6k3FaHOdY
Pyr+H1aHKZsbC5F0nqN0O3pV8TMfg5PJ0Xwicjr47HeuxoZW20BwPlZvVPpqPIic+ABj67BB0/qk
cjAddE8LWiyuwIcO6scbeuXl/U8R+DP/APGNc9g2oCrUMXXnj+Hi4QYRw4hendW6PjdXxXAtAcBy
uIz/AKbyenh5xYw/4PK1z1J4alljMdPNJb8iW7/p4Czs/qLCDHBIfF0oOoOzRIWZDXN/7oVVkEsx
pkTnE7Cgu/x8SeayOOX05bkdqA7haU7HQQRvaCBKNW/hTdK+mpZCJsxhijaeDyVJ1uYNyxYaIwAy
hwE/aW5GoXT8q2Oa527DwtHHDZIvUB9wGrbusFjvQlDmb6lexskjWI3U1wtoPY+EtytNmZ6gN+0u
FD4Kni+pMiLp7sCV2u3am32CyYSZmvcwnc2fhVrdLIXg7A0CmXGs16Z9LyMfhuyyQXOIFdwF0bZW
yta8V+V5d0LPysPILLHpSNv8LqB1136dscW57Fdee45dcuxjFi7RPNCwszpMmRJjtMvLhzSvkENo
ldNY3BN3dspEEY5UhNBQRTHYNHJTRM0bHv5TsBLiXduE52dakMfKekye1NTGq0XacBM3uiQIQTt3
Q+UTeED9OBSdJJCJJJJSJJJMpETQUT8hkexcLRSglhFn9lTEDC7e3HyVJN+qDjsi1ghOGNa3ZoTN
I3BSDONjZZnVItYFjhaT74AVbIexopwtGJi9WLocWMgc+0FZ8WLqjDZKNjdXPqTKaHRR3sw6nD9i
qMc4bEJXu+6qFLh3PLp8a0WxsYGhm7jSpZBMETgw73ZV4Pa2VrTe/wDhZPVZdEbmtJt3fwjHeRQj
gD8gyj3Fwtt9lqQRSOhB7nbfsqfTYnSMa/gUtPSHir28hSAwaRpHB4SAMs+lvARzO9GIjudgpunw
enEHuolx/sstauBtRAVudlax4wGgD90DI9Rae3ZXI49Da7lakZtExvZSNbXCQaAipajASLSr5RUl
Sl4CnT0m/ZMiNVodCOklLEZFIKUx4UdKURFtfhAQpqQFqkABICk+/CdZxuG7IDaM8FICwlIXC7Ql
qkcN0NIMRlpTEbqWrTUrFEJbfdNo8KUt3QltKO4hLExjCl0odKzhlV3MBBUT4tvKtOYKQFuylKpO
iFKF8Q7hX3MtQPZazY3KixXhhLe1cLF6pGDO6hsVs6dLuFm5rdbyaXLPLPPOXWFJC5jrBUGRE17d
titKaLYm1TkisHfladOordOyS2UwOdTXcHwtvpPVDFmDGncCx5oOWPj4ZkzWsaO92pXxa9cjTu1x
AI7LFjj1zsdmcoYkxZqFHsSpMiFk7PUbV1uuT6plOzemQztfpliHvcFofSfXH5rv0c4uRou/IWbH
mvxWeQ5/TcTMBZJGwSDhxC5nqAzei37omw9iyPddb9S4UrG/rMY7t+5vlVsd0XUcJoe3W1w3bV0V
c9Z7UcZL9TB8YOlzj5WPnZT86nO7dh2XUdW+iRbpcWTQ02dB7LAh6BmjILDpjAPuJPIXp+Pvj2kO
LMJmiJ/3NqqWji4M36iV8tshsGyrmD07D6fI6yJpDv7d/wD9KTIndkOLZSGMDtgP+qb3PxuK2A0N
dLoLudFeQrR6a9gDtOlpPB7IJ5W49NhaCR47qaLKfJES9wcBtSPs3KsAMiY1oNkjsrsWSMfQXsoD
egsxgv38NG/Kl9Z2V9jg4N2LU81Y77pn1DhPwGAv9M6f5u6v9P6hHnMdoN77Fec48b2SsL3Wxo2a
O35XYfTLJJWer6umJnauV3561y74/XTtGkJEhw5UYL3bdj3RBpa0rq5F9ooIHPDQCT8Krl9Qjg9j
QXv8Dsq4ORM8W2m8qTTExPFEeVI112qupp0+mKA5CsxigT5VDGw3uiQtThBheUTeEwCdvdAEkkkh
EkkkpGStJKtlIx3FWoTENRIO6eXJbDyLVb9aHWQ0pKcuLRuojKDdKAzmW+yBttJPZQWBM4mqWN13
qLYNg73Aq9NmRxMc43sOKXOzQxdWimkYDq43Pdc++/qNZEmbJ1PK1HZkhpzzwAOVYxy7Jza/lYL+
AOAP+qiw4Wh7WFpYyU6APFcn96V/GY2LUQL1u79wFx+32dvjnhdx4y95e4GvJWTnxjJmDIjtq0la
mPlNkxHaQa4/CpQwsim1WS48DwtOsSxY2iJrBtSnawNvwEbW6m/IUc7vTZVqKBzDk5IA3b3/AAtS
GMEbDYbKthRAAk8n/C0oNJOho3HJWYqkx4yO6tsbQ35Qxso8KSqNrcYp6TWn3SoKBdkkuyS1yoSS
SS0SSTWkhGdwo6Ru4TXsiAFJinTEJsICOUO6PdMaWGg9kuyQTqMRm+6YhG4d0KABJFVnskW7FWkF
JiEaZOJGQUNKQhCQN1lIiL2KAgcBSPNKI8KISLUL2hTIHVW6MaitK2ws/IjDrHC03d1RnaLJWLGo
ypYKBBVKePRuFqSC7tVJmAjjhZxuqwcMTCfKCDLIKb8Kn0uYetLjyb6gKvyrORGXsq+OFnsaYZPU
HLTupjF/FGl8uO7gqv0l56d1/Hv7ZCWu/wDf7KxJfq+q3g0VUzH+jksnaL0OD/2WYx36buT9RxQd
Wn6flexpNRyHh358LI6ZnDpXVsmFzrje4Obvws/6r/jdVdLdB7A/f8LDgyJYshri4ub9oLlv6Sx5
rMen52VBhRjIcLifQJHlVnRdNzRqZLEHGq3Vbpkv+qdHlwpSCdHtJ89lymb0+WfGe9vtnxhZrY7f
hcueZuUOkyPptobI/FLWyOva9iuVysbPhe9uVAWFp7DZyzcfOzS+25MzA07gPK2MH6hzxKWyubkR
V/8AObZH7rvPjxqUMZ+wu5I4K0IsLI9PUGBrOdUmwCGT6j9FhIxcZhPcMsrMz+o5XUCPVnc5vZvA
H7KnNai3NM5jwGuErBsa7qWGB0IEzdTWvO3gflUcGOR2RGIyNJ2d4C3cmJ1xMjsNB7d1rMduedjS
wWjMwpPUDZdPNUtLo3UP0k7Y3/7TdhZUH0vh47sp0DwA93Ht4/8A2tDrHRX47jPjEFt7tIXb43Hv
+OjhymTRgsIN+CociV7dhIR+6zujZWNPDokpkg20u2Vz9JjnU4sAHm101wsxHA1gdYIcSeVdYXNF
FpZe+o80o8OCiXMaAB8cq6xhbuRutRAihDa2q/8AKsgUEEYq1J2tSaje6cJhsaT7DkoM9CbvacIW
kb0jWUSSSSgSSZJSOmPCVprUojdCx+7hao9SkZjxODAASOfCsZMpYbvb4VXLdE+FpeRskyayo+qS
Yop7BJfHyiH1HbDWFv8AlRekZ5HGgGdko+kkOLoyaPN91i2/jf0QZfWpZYjpg0bcrJ6fnnHyjdhs
h3W/+iabFD91mZnQ3DU9pG264dTrrzWbzIacCTIc5o9rmHSfHe1HKalDQeBt/ZBj6248l7lrSBf/
AL+VNjR+tOf+6FR14nhP0uIx4pBO5O6jmv19DW0Af7qyZBBE4H+VQYTzmzGWqa1LcW2t0j3cKlKH
TS6QDXlXpngUAeVDC/SXuA2buUeTEzGaQ2Jp/iECz4C0cdmlob/c+VnYAM8jnDf5WxCwCh4WpB1U
rB5RpBKksEmtOmpSJJKkgtz0ipKk6a/hZ2oyaj5Tpvd8KJAeTaBESQhTAE7JinJTdlGBPBQoygOy
GpSCSYFLUnPC0zims+E9pUs4p5CClaR5SWUE8puyc8plqGBJQE7oyOVGeShBd3USlco1EBUbh3Uh
7oDwVlqISeVUnG5VqThVZ1Y1yovYd1VkCvvNAhV3tFWubahINztsqM8X3luxpakrOVWlYKIrdGDF
SKX1Ii0H3A6VXzLOQ6Lggf4pWcNoZngyUGNOs/NKpkyCXPfL/K/t8XspixT6rr0Ykr9yWbk91kTA
uJbew3A8Lb6kBJiYzb/lv9ljTAtorpw8/UdF9JdQLfZe7Srxc2TqjnuZoZNbXBct0vJOLnRkGg81
8Lpsw+jI6bkBzXiv8rz/ACzKyyHYmPjdSkw54w0jdrv6hyin6S2NvqxSDRfCu/VeE6fGx+oQi3lo
aT5K5uPqeQ5noyuJA2/C6/HbYYWZE4SlzTseR5UcxLYxtsQpnOD4yAb0qq6N3pgusLtyW909+LHg
W17RK7alf6THJEXOEhcTuQd1y+K8sefcux6F1DF/T6Xj+I7YKsdvj7xo9N6zj4WR6sjCDxd8ro8b
6jxc4FobtW9ndYEf0p/qjy4EtaHWpJvoaWFrnwyvDj4K6c+I4/JZvgHUSBkHJhkcxrd707rT6T1w
TxGMAuI21Af8rkc2fqXS2HFnD3RX93dT9GkyXkz4U5c1v8ruf3WozZK9NxRcYJN7KeqXP9E+o2Sw
aMoaJG91uY+SzJZrjdYPC6RzSI62pNo+USKY1AnoIUQFoZhAIkPCdBOmTah5QSzNjbagJ7tItR/q
WNO7wqr86PJY4NkAWY/Fmld7ZDz2WpE3JJxptpWdN1CVpLY22VFj4+QRpdITXZXMfAax9ndSUMaH
OnJfLJQJ4U+R04uFucfwtURtbdKvNG55ICyp4YE0ckb/AGbkdkn9Wlgbo9IEnwtCbDJJPcLMyYms
mAcFi3HeYrNzs2XW8MA0njyocrqOTM70tOkkVsrhLdZa3axygGMwnWaLgVj7bGvpFPRrgDHbOI3U
uJjiGQyufzwFbbDGQ6x7uyb9IXTF2rbTQCxhkxWyHetrazfdWsKD9PCI63O5QQ4wZsBuFcEdHZMK
pPZlDfnlQZrzGGwsFE7lWJXNE2/bdU443y5b3clxsfCk1ulx6IxQ45+VqRAX+VUw2VGO3lXmNFLU
c+ju5T6T5RAbFJagAknPKFVR0PdOlSNMOhTpqRFCAS/dOmWvwhIJ8JtJI7I03u+FakZCYhE4blCU
AxQOGyNMRbaUUVJqREcplelDUnadqTG0QbSjCG6bynAoJEINqMhNpKkpNWyhqIgqNzaKnIQOFqOo
TwVGVOWcoC1BQEcoDvspzt2Ubh4U1FSXY0qsu6uygWVWe3lZaim5l8qFzdqVskKF7btZkblU5W0F
VeNyVelbbVVe0bhFLMy47a4tO44KzDqf/DaCXkU0rdmioFZEjzjSuLb1OBDfhAvpDmOa9zWAWYho
2WbkR64/kK3Iba7etff5VeUEMB32FFb5efqKDdbQxx2IcuvyJWP6L6gokgNXKTi2We261em5Bn+n
543Ot0b2kfhZ+XjXLG50+duf0ifDd7pMcW0fjdYsnS4Mg+owCq5BT9Ly3YfWoXknTM3Q9vkFWGNj
gy5oWu9gcRQHCxzLPTUZZ6a7GaSx2oFPPCZcWN2mvIVuTViykk2w8KSWL9RiB0RAoLrzUxMWJxmN
ChxZW30X08XqUYkOphcDYWUYpWvLadZNfldj0f6NnnxW5DiacLFdl05mjXoPThA6Br4OCFbI2WJ9
MRz4sXoTWaO1reO67ya575Y/WehRdSheHCjWwC5DomLD0jqmRjTuMYkHt1cL0ULjvrLo75XCeGMk
t32KMwwDIAzLa0tD2PPI7LrsCAY+O1jSKralwv09nPjnDJhq4FHsu7xZRJHxVJlVizqS1JavhPqS
NjVAtE3uhCJvdDM9FVpJ0kJXna4tJaaVNxfM0xt3vYq/O0ujIHdNBjiIfKUpw9IiiAoUe6txYrYx
t/wpqTj8qiRiBrbpIU3uiJ2KqzSOANNsqSzqA7oCW9qNrHyOoTRbek4/gpRdQfIy6LSPKyJtW8vI
ZHY2tZOZF651tNFPl5DbsmyoW9RZpcdJcRtSx1Y683BwxsbA4OI1VQKib7bBrdU8iR87xoJarMLT
7QTZ8rlrrKOY6QKO6kgBc+zwQnkgs2e3ZGwaeP7JIY208lHI7Sy0jQKjyX7bb0k6pzEAuvcuKLBj
1Sk+FFIXGceGi1b6W2ved7QsbMLNgBwrAFClFAPapluOVJJJJICUJ4KJx2Q2K5QYVJWlqFcobHkK
MOkmvZK1I6cDZCXUELXc2VIf/vlKvlDbUQ4UoYi0BbSkSUsRaUKl0pi0BKiIi0GlSpqT6KOkQIAo
pUioeEWryHnik1H4RgAJ0JFVJqUpGyGq4UpERCYhSOHdBVoMAQonBTOCjdug6hIUThuVOon1fKsa
itI3dQOG6syVfKgfQBNqOqsjKJ2VeRpAVp7h5VaXujGuaryjZVju5WJCoCPdazY2ilZYIWN1CIai
e44Wy+6Kz82MFpKJCwiaJjdW24Kjl3BHdvKkyWlr9SiaRI7VyeD8pcelbKiuM8/+ibGlEGMYmm9d
aj2pW54iYdd+0bKuxrCKsV4TfMcrF6SEvOLIzkOHCtZ4DOoTOHFhKF+iBrj/ACuCAn9RkvLhesrl
6WLLnQ5MnovZWoCgArY6aIcemjSPCbpn6ePNiZkxjUwjSSuxlwcPKYSDocB24Wsv4HKdF6Q7O6i1
sjAWxm+OV6XjQNigaxrdIAFDwuf6T079HkCSOTnmxyuljcXMBK9Px+nK+yDA3cAD9kRO2yICwmOw
4XXlm03YqvPB6z/cARVbq1SaqKr5alcP1rAPRuosymR2wuF0um6dmw5UTXQOF6QSApep9Ob1CAhx
3HGy5LHkf9N9RkMge6B3jsVmQ2+HcMfq52KkWdg9QhzoPVifqCuNkoeVtzbgGycCkzeESwSSSSUj
JBOkpEmTpkfqMQoZS1t7hHKC5ho7qlKx3BO6QcwtlBvdUc5jIWbCiVYdkDGjLjufCx5cl88lvO18
LNPPtHokcCS22+VTez0ZLDvb4Ws7JjbAQOaWDkesZTpbsSuPTpKs7ndoV7DjJYHHeio8OI+npe0W
ArWJbnPbWwRzG5U770m/KiVpzPab4IVZpBNg3S1jQi0BuolV5j7SB2U0jvaFDkOAa7wQpRV021zv
Oyt9MZx4VZgIx68q/wBNZ7QiNb4asIq1IhZsCfKJdI4kgLuU7jsq02S1o+5BkSPfQ5UTpgO9rMyu
paHgarvsFEM0nfdTX1a/6ltcIf1TByVjzZpa0lUpOoOLTRIVp+rpHZsdVqCH9bH/AFD+65b9W9+w
eQfKjllmaD/GKj9XWnOb2cP7pv1ja2IXHDqM8Qq9SX+syA05pCD9HZNy28X/AJUjZ2nhy5ODqLi3
UCd+N1ex+oaq1WCmC8Oia/flGHArPx5tYu1cYVMJkJFp2909bJSMt2QqWkNCkylHSdPSZWIv3SSp
LSjESYhOkrEEqJ23OylPdQTSaWm1lBe8eVXdOxt7qlmZnpgm91i5XU5HE0aCzrfPDoXZke+4/uq8
ubGBey5Wfq5YOST8KlJ1uUu4NK1uc46yXqMYv3BVJOoNLfuB/BXKzdUkftdKseoyNOzz+yYcdU7O
aeHD91E/qHbUFzP+ovPdI5r1KOi/1CMupxCPW1wsEEflcwcgu5/urGP1AxDTqNLJ1tuNk+FVyWBz
CixspmQw0d00httd1GViZkFsI7jus3djr/utzIjIu1kzxaXnwURjqLOM1s0ZbV3yFWfiNjkdY2Gw
VnDidE31GlXciBskOsbh4/sUsYq4rfVYYyfwnjic1ztqIQYNwZW4sVQtdH0/pzMvFdIW+5c830z6
ZDIy+NriPezdaGD18uPpyOLS3hRy40mI1xcDuaWS8O9egCT8BU2MdO+6Z1WJxFvb+5XR42Q2Ro07
/K856R0yaeQH3ALt+k480Uelx4Xq+PzHG1stO2yT9gmYCGi0VWF1iIcBOmTjlIDRB2NLJ6/05mTh
yFzdR8rYpDKwSxlpQ1LrkPpOf0HvxZRoLdxfcLqm7rjvqmE4OTA7Htm/ucF0/Spv1HT4pNWokbkI
5odS3unTN7p0IyQSSUiS/CcC0tJQoTb33TlICknK/WvxE77SsvOllb9lcrTlB07KnLBq3cClmssx
S5BGtSzdOYyOwOyus0tIAanz7GO/TyGos8KeHNHeQitrUseK2V3t9td08OLK9we4AWtOHEDAVy+t
alV2QmJn9XypsZgBPt5VkQ0N0QZpBoJkbiKVts0+FRjiLXOaBsTa0iLChDBqKrGpVdzCYwKVZ7P4
Zadza0XMppVR7KcUNxAQAyqV7AbTQqex/ur+CPZ+6zCutOyIn2k+EwGyRGxA7rq5KOZlObsFlzSP
ffO62pMX1OQhb0+M7kIMuMCHpTnO9RxJ3Vv9II2rXGEwCgdkv0TO+/5Rh+zn5YtRqgoHRVY0BdI/
AhPLBajPSYCrDO3M/ptjRF/8KF0LuC2107+jwmwDyov9Hhb9riPyrG5255uHE/YjS5L/AE/S4tc3
UDwSF0benNab2P7KRuCzbbdSvbnI+lOb7mC2nt4WjjYILd2brUbhNF0aU0cAaKCsYvarjwaRVcK4
xu1ohEAEbG/CYzaTB7UQ2CcNThqRoa2QUpSEOncqUqNDpUhFdkPa0NhHBTainsoUgrTWlaBx3KPa
J7j2VHKLiCLVs91XlbdlBjEzIC6y40smfHe6xRpdPJjiXYqM4IogAH8rONzpw+Vgu1Gg79lm5GNI
Ds1xXoEvS3OJpoH4VGfomu9t/wAIw64OTGeATR/dRtglN+y/wu0P0lJNIC5xrwr+L9JwQt9xspOu
Dixqb7gQfwj/AE5NgAnxQXoLvp2CtmtNeQqz+hgH2taP2UY4Q4sgadQIUM7NLTZN9l2uV0I6TR3W
Hn9JfEDqA2UmNi5roJrFuHcLfilbNGHN4Kw5MLSS7TR8rR6UT6ZYSTXFrOKJcpls/Cx8ptLoJo7a
sTqDSx23HlRt8JMAaseuaV7EDHtdCeDx+VndOeWsk4pWmBwIc00QbtTmKXE07adLmmxfddJ0AgxA
Df4WfMwTta4jZ4/sVb6PIcfIDe3ZPxzy59bjT6l01uQdmbV2VbE+nmyEF7PcPhb0EQmAdWk87K7D
A1h1d12+k3XK1T6f0tsNCqWrHGGDZM34Ug4K3IxTbp0wTrQN3TpiE6iJB5RA3snDdt0LGZ1fAZk4
r3PaDQvhZv0o1zIJacdGqtPYLfyoy/He3sW1sue6FOMHMnwZdtTtbL7onsu9b3TpgnQCSSSUibyi
Qg0n1fCyZTpiLS54SNjuo7A1ugcwOBCkTUtMqoxqdaGaAPbpJsK32QaLKsSmMVrGjbhG2DvsrD2U
Eg32qSD0O9pywURSmrZAQgyqpjo0gLatWZK8KrJYcsV05BMdLCVUcbtxCuTt1xKmR7CstxXad1qY
TaYVmNabWriimIhvpaA2SSH2pALbnRaURYEhwiPBVEj0/KEiu6kUTjykmIQOdQKF0u5A7KnlZJYL
1WPhFpkWTIAOd1E6Vou3D+6zcjLcY3PbvQ8rMyMoj7pKv5WdrfPLoTkN/qCOOZp/mXIy5EraLJzv
xuhjz82B969QV9q6z4tjt2yAhG1wXMYf1AA4CdhYT3W5jZUeQzXHIHDyDsqXXK/HYvggowAq7HWL
UjXbLTll9JaCQCZp2RApENSEhEhTigCEDjQKNxq1C926w0ElC5/yhe6tlA+XSmNYlL/lAZB5Vd85
A3Vd+TzujVIva/BQE3e6pfqfBRCVyG5Fq2jsmu7ohQ6trJQ+sGgkmh5KtanKa0gWDsLVOTPiZsZW
i/JVebqkAc0Cdl990aZw0zIAdyEweDxSyj1KC95mb8e4I2Z7ADT2/sQjT9Gi5yjdR4G4VduUXbjh
HrJ3Vqkwz26gQaWZmYrJA4EWtNzt1Vk5Tpc7k9JFEt/squPhjHkO5Oryt+Ue8qpJECeAhKkrPaVz
fUnFshA3HhdTI32E+AuW6nRyKRjPRsMhzXNGxpXcQEksu1lwyaZdlp4diUGrtOObVgLnY2kCnMNb
q/i6tDHkccgchVMVgDrPDlo4semVzRwd7Wp4N9Og6fKx7QdW9LUjFj4XMRRujktrza6PCeXQjfdd
ua8/UTgUiaKCQT3stRgkvhJJIJJJJSOzlEeChA0orWWojldpiJPhcbNmtk6+6Qt0tiIH5XV9SyWY
uM9ziKDbXPdK6Y7MynZ1AtdwDwR5TE9BCdJJZBJfukkhElSQBKfSUomhPRSYCERNIxZEZ5KZOeSm
SjUnApOkpaB4tqTPtTng+EMfcKREcqN4ptqU0Ao3m2FAV3uBsKAiyUEkumXlSNJcLXPp24gXfY4K
k8WStBw2VWZmk3aGtVmt91rTx2+0BURZNrRxx7LVCl7JDZI9kksWiHCIlAHJtXdaiorChke1nO6e
U+1Zedk+ix7mPJNbCkW4uYj6nlnFaZnn2N3I+FgZX1A0lww4zM3jU1DNjZ+fkxvy3lkGr7W8j5K3
8Hp+Hjx3BEy3ckD/ACnny3Z9Y5HN6rlQObDNG9hkaTQrYKFsrmxue5oc08alqfU3T2u6pHM+ywMo
DyqwwDNgytY0j2kBdfpMcr8ms2LrjJnugjfE5zOWhEeoPjcHSM/hDmlyeF0PMx+q+o5jmta42fK3
3j1PZRNdvKxOZTO+p+ujxnx5MbXadIduG9qVlmPPhu9SIuZ/4Tsf2Q4GD/8A5zARRDApMbOdAPRm
AIGwK5dc2enq4+aVqdN6t6p9KYaZPN7FazHitjawHYsc7PWgf7uaCsYGc5rzHIwtcOVc3wz8kl8x
utepWmwqbJA5tgqWN63HCxYQ9kgbCYnZIkRyFVpHVsrD6VGdxDys10kBNMGd1nz5tPpNmzkE0eFi
5eUQTusa6Tlbm6gdZGpQjM1k7rKkyCTaKCSnX5VpnLchkHJKkdnMiBLiAB5WHL1H0fYzd54ARY8O
v+LkvI8AnhWtNN/UJZhULN+zjwqeVOfczIlp1fgKxBN6xEeOb8upYX1NiOxnRlsjnTSO3s8fhb55
1z6+T6mkz8dxidrcfTPub5TnID8iR5jpte0Xys/IxXYnT35Eo3As/KycHq0eU5zCS11bJ+n4z/ub
s0jYn6shmmvtUAzY5J9EIIFc3ysvMY9zHP8AUdqHyreNhOycNmXA/S9o3AHKL8eNc/NvltY/UsvC
aN/WBNaT2W50/qceWKun1uPC4yDqL4SGTMo/1ErShAOmaJ+432P3Lnecdp3L6dbqUEhUeHkmeEEi
iBuEnuJJpBRSe4lVnBWHbWoQLUEEzf4Llx2c68h/ldpkConfhcXlhpnk33tajHSqDRBWjiyaX3xY
WcGkFWC4sLSOwU5ulxJGyMN+QtOI6ZPbawOnS6sbX31D/hbsDvY13cphbOJTwCQtrCoMWPitprSP
Cv48hZxwuvHpx6aYNp1XjfqFqZpsLpjiKilRStLUhFRSCVpA0pCIKG0WtBaoWf1aES4ztRPFEKj9
NTPbHJA4W1h9jvhS/UeS+DCcGclS9GjBw4nhtFzbPwguuSSSQCSCSQQodnCJCzhEtQUgk5IJEIp/
Adylp+U+k+EtJQjaflI7DlJJSN/KVEDRUlFC4UtREVG77CjG4Pwo3/aQqhkZbtEotWIXW0BVeova
2TdPhylwJvhcu3bhfG4VWY6iQrWoCPblU3XZKy3gI26nUtKFulgAVKFvuNK+wENCgc9kkkrSzPPs
JKa9qTnhCtGGJO+yruiDnXpBPyrKbSFm+TrPlxWkEaa/Cg0OxSSx1NPYrX9PnZQTweoKI2VPBl2Z
WL1AszMf3t94OxCqifHxIHN9QP1jdruQtp+FQoAUqmR06NzHF0bT23C6z5PrGP8ATK4abOhZkTeL
4UvToP1U7ZXt0Nab/K6ebo8LHao8dld9k3+nho9rAEX5Ndefhk/Ub81rY9LRwKWPn5EhNhp/ZbQw
zdFF+gB5bf7Llba68c883WL0jLfHMdbnBo3pdNhyx57HSBumRu3HKgiwY2b+m3+yv4oZEKa0N80i
HvqVZx2lrPdyrDDRUDZTQB3UjHaitx5qssNkp3GkMW4SkPKQCQ7LOyXGyFcc7lUMo/csV04Y+c+r
3WDkyHUbW1nHlYWTy5Yd5EBddqWPV6Zc3nsq7T7t1cx5GtYRsqRK7po+ns/UTkvkcaa1VYepT587
2vOn+kBak/TcfP8AdISTVCuyji+nY4pA9srieEyMtvojGRQhoqyNz5Wd9ZY0gZFlxtJ9N26nihmx
WjRI4/ClyMibIxzBNCHNf7QV357kebv47ao5GDj9T+nHyRTNe4s9wB3BXF4XQX40xfJ7nCwFvOwM
7p0kzcM64pNi0GqVZ/8AqJB1Yr677Lf2l8sf6+kGQ1sMJJ7mqHdb/RcIY3TGtkFEjVR7LO6fgSPm
E+XG4tb9rFsSufLEWgaR2pZ661rn47HP9UxopJnADftRQ4JlxpQ14L2DsCtN+Hy4D3Dz3Qsx6cXV
RXDp6fj5yNbpeQ0uLg0taexV2R3uO6y8aI6bcSD8KywEDkn8rLoOQ3x5QtCKiU7QjRivmbQPPwuJ
yP8AdcfldvniseT8LiMj/cd+UxjpCzko5LEQcorJPtU8ob6DSd/haYXukymOFzHctO3yuixHepCC
uX6XJTm3vqJ28LpsJ9RVtX5Um/03IDmAE3Wy2GQ7ArlukyaZyy73tdZCbYvRz6efq+Txtq91NGd6
QNFKRgrdaYStAKehRQj4T0VAySVFKipEhKJCQSCFKOf6+HS5EMbAXb7rbw4BFA3aqGwSGIxzw8t9
wVituLQtbCSSSySSCSQQodnCJCzhEtQUgntMkpaRSSSUAHkpJyDaZBJA/go0LvtNqhRMO5tDIQBZ
RAeFHNuEph9Rb7nOHJ4UOPK3HLWk+5wVzKouO90sz0teQXE3XC5deXXjxGzHMXsIQ0UMW0fKkCy6
Q8Qp37q8000Kkz7ldb9qhTd0k9G7TLUYMeEJRHYJjxaKoHskkeCkOEE97Jw7yhTWnVgnaSOFE6Jp
BFbI9WyD1PKjJiGTHbWyhdCBsrMjlA8qbiu9jWlRk7bKV+5UdKKIPUkRtyWkHsnYwg7BQqdjr2U8
SijjoX3Vljdh5SxUseyTuCnbsmdwUaogfYWdk8uWhM4Vaozi2lZdeWFnXusXI5K2+o7FYzxqcsO8
nhSoBylaAAU74bd4pEItXBWozU2PI5pFcLSgkPfZZ8LaFK5GNrtaYW9Rd32TuiL9N8NQRm2qeIEk
KOIm4TNV6AP2QnpoLX6W7n5Wk2qKVfKAzh01rGkXfdAzC0amkfP91qemCCo3tNk8qDMlxLbVbhVz
iC9+VqvYCUGgDspuKcUNbIjHVqzoFqN43Ky0r7cJwNk7m0SnHCJFVXqH/ZnfhcPnf7h/K7jqRrFc
fhcPm7vPwUxz6QNBcnlLg3lKPYIms1F19lphLgW1kbuDZXRYJJYAHWSsLHbcDPPhbfThoG6k0MB/
o5A/7y7PCfqhG64aNxY8OJ27brrukSa8VhBsld+Lsx5+plag4UjDso2g0iZytuaVqJC1PYRUdLsm
1BOgBSTJLRE3lEEzGp1QVrAWlpSBq09jyubckNSQ5T88bpqPgqR2cFEmaKHCdajNJJJJKJJJJSMh
o2dkaawsqBqkEh9qkcRVqB7rJ8JMMKpQZTtLSPhO6cAkAhVMnI1WLpFM9qL3D3XwFnSZQB0s4vlS
5s1xPa3juVmNOzd+65u0dDhPLmgK3Wyo9PPsaRwrzZB3pDRN+5XmbtH4VZtcqdh7WmM0Z4KGtkRC
bsU4sARsm7IuyY8FDKN3CfUEjwUNIhPqCEuCZ10gPCmpBFw8oLSUdlRw7jaiJ8oyhoEbqhiIhIMJ
UoYKCNseylUDYSVMyIAcI2tpGG3woaAMCmjHdN6ZUjRQQDgbcJn8FEhKhFWfZioyuBaRe6vZQOkr
OkbyfCK68MjqVLK07rU6iNSzT3XN6Z6QlgsomNG6IhPG3dUoxJHHanjZ8pogFOxq6a52FGNIoK1B
WygDCdwrEQICtUTgA8J2/dSZvGykY3clTNFp3pRv5qjSmra0B3KNEiDQ0drQEDehSlI5CEtPZGty
IDGVG9qndYtQONlGtyK7q7pDdE4CymDUwWKHVnVjOAPZcRlElx+Cuw62/TA5clMyya7qjFiKOM6L
5Ugtm/wnZ7GImU86VpirsDQYonAbnlaLXemKrlVsPQ2EDTQCsRPY9zrO6mRzPLIgQL1f4XV/TeQ2
WAACqGwXJzEaR7hXFLovpeRobpvsunxufc8OqakNkm7gUnJ2IXVwG07IkDD7UaUSI8FCeSiG4QgF
IJyDXCFqSmYdgm8pmkUn7I1Y1kkkllHaiQtRJgpJJJJRJJJKRJrAToS7wgHseUJ5KROyjMgANlBh
SvDWkXv4VV7yGEIZZS52yINJTCq+m7cqpnj02Al3PZa+igsTrTx6jQEX0efbNzD/APDOcOKWdi3K
5aE7NWI8b8KjgR+m6yuL043sY0yhtQ4RtefNKHHd7UH6ipC1SaUOTvpcVcjdvd7Lm5ZzHJYOy1en
ZgkAF2qVmxrNNhP5QxnU2wnqzytxjTOOyHsjI5QHgowgTHhEhKMwwB4KE8IyELghuUGoIdCIbJWq
FHXwlv4/wpLHlKx5SgRnUeEYCTRtx/ZEEDDNFlSNFJNGycBIOnakkBQK1jNOhJT2hPCyohyCCwrO
lAANLQn+0qhPswlDryw+omlnEHdaHUeVRPCxY7c1GiZ3SITs2KzjcqaNWY1WYd1ZjO6WanjG1KZo
HCga5StKtZWGe0UpGqFp/dStNhSxLYpN+yEGktSpVgHto2olOd1E4ab3UUDiq7+SrDlXk2u1GIS6
iUtWyGrJQk8/CYLWL12Q1p8rnpXNba0+u5WmVzb4XOTZduWo49dYsSvFbFS4jdZsHsqDCZGl1rUw
hoaPwpmVeYfaIyardMJTrLW7XyVU9UmTnhWIQXu/6qS7I24RXPla/wBLuIfpJ3WWwao6K0fpx1Zb
m2t/G59+ncwn2BGeSo4iNAHwpWiwV2cBx/aiTDhOlEib9qFGzhURO4UfCl7KNzaUSCMcKJrrJCka
6uUCNdJJJZJ2okLUSYKSSSSUSSSSkZCeSiQnkrP6ojldpaaKp6nPcRVq3MLFIY4gLKijjhrchSUG
qTauEL62TEikNMK5nqbnSZAorosxxDDS5qeTVkUfPKzWuZ5A7bFdaowvuUtsCloTUISDx5WZjtvJ
vkFcnpnpsY7fYquSNLybVu/Ti/ZZ2RPrabQkcsofHzuE2HmvgkG+yoySFgJ33KOB1sJKljtek5f6
mGr3CvrlPpbM/jviJuyurB2XTmeHHqYR4QHYKSrCBwBKVAJFEdghQ0EjZAQpNk1LNhQ6RaalJoQ0
fCNXkKdOlShpxVcp20mFeCja0UrF9jjhEAmA2RjYLUG01fCRPtT2gKVEZcRYQlx8onqM91kwErva
VQmNghXJD7SqUvdDryyM9hPCoFlLYljDxRVGWIgkDssusUjsnbRQS216THXdLLSZh91KzFd7qu3y
rUQ9t+VFOxvdTNbYKjjbsp2MKsZBE5xcQQduFYZwkG/G6VEFWLRJJBPYFqwhvkKJw2KMmyoyd6Tg
Qu2tVZTurb6Fqo/koIDwSFBOQyORxNbKfssz6hyRjdMlcOapa5jHVxxHVeoerM/SSfdSy2vsmzaj
mkLpHOvkpm2V0keW9eV/EkOrT2K2WDTGXdlz7HFhDh2XQ4Rbk4paaurWa1FZ0lOBtXsR13e1KnJh
yMF6S4cghSYsh1VRB72hpuw7i67KbpbjD1RlDZygw36m0rWOGjNiddFa4vlnv07rGNsB+FYYaKrY
e8LfwFaaNrXoecY4TphwnUCRs4QImnYqUEhNkG0SSNaxXPtdalaRpF8ppGCkDHE2lluJJJLBO1Eh
aiTBSSSSSiSSSUjITyURNITuVlQxFpDZJJRI8KJx3Up4UMgIabVFGf1Ob04zvuubld6jwbrdbPVd
2ndYrOT4WOnX44leQ6EtcaUOLjgSbFSVtv3RxgNWHZJPeggKg+L205XHybGisrJynNkq1GKuWwMd
VomHTEo8p2pmsqs3IcNidlNyNPoM/p9WbZ3JC75htt+V5di5WjqETht7l6XgyepjsdfZb5efv2tD
hMQiHCR+4p9MTyAtq0BFFSkISNiEVpGmIR6flN+6kBJERaalnDoaQFpvspEJ4UTBhKNuyYcBO1TN
ggkmsJXsmEJfun5Tad7RAK9oJFhQuFGrVghQvbSsMV5Qq0oBBVuRqrvHKy3yz5hRWfMd3LUyGUFl
zjlFdozsppIsKFh0ndXHMsKvJFXCy1FmA6uPCvQNsKhhg2QtfGisC1YLcHFHtalY3lSMioJw3dLF
pmNSqrRgUDug3QpSQuRihdIFHUbtrQHlSO4ULjuoo5DYVaU712VgkWoJKJKhaisUuU+t80xYgjH8
5XVO2avOvrPMM2d6V7M7Lpy593w58O1E8Iwomg0pWAnYrpHnTOHtC1OnT6Q1vNhZrtmgKeJ4ZpI5
WK1zXTwNa5mn3PvkA8fshf06aMGaIh8ZPBG4VTDymygW4h3ZwW5h5sbCG5Ee1fe0bf2WXRDiBxIs
UrQv9TG8bCwpzi48n8SF2gnxuo3MDHNJINHZPLPXp2/T3A47b7AK2D2VLpZvGb+ArrQRyu/44fqR
vCdMOE6WSRtAAQtaiGwRph0ydJZIXbtULTTip+ygcKetShupJJLNR2okLUSYKSSSSUSSSSkF3CZv
KcgnhMAVlQycbJFhpMNlNSnO4VbIIDTZVg8cqlnEtad1Q6oTxtyGOF8LDnhdE8gilfZkiOY27urk
2NHlxW2iaXPvy68eGPG0EJPGnhTDHdFbTzagnOltFZblROJIO6y8xtSEHstAPoocjFE41AbrLUZO
QS6EtaLHdUhq3Onha7YGQ6tage6BjTwptktcW5DHkVRC9N6HLrwWUdqXms0jHyUHDld39JZHq4IB
ddLfNeft0QKK9XKAHawiB2W2IdCTYKJMRsUNApLSE+6e/lUn9ZD+6HSiSUUZQkKQhAeFHQp7SCRN
BEqkK0TW2hZwfyijd7q8J0j0ImtoJF+kEqL9W0c7ISRzLUT2KWOVsjSWmwkQEjVRzbBULowVdc27
UZaKIRY1zWbPCC1ZGXBRJXQzR7GlmZMYLqKxXWVkNhJFAJ/0p7tWzj4kbmdkOY2KCNxNBZbnbDwY
3eq8V3W9jxDTws3EZUpfXJta8JFJkYt8nDdktNI0qWsGo6QuG6kIQOFFB3wCkJ2RFC4j8qGonmu/
CgkPypZSq7jspqULjtQUDzuVKSoHuq1C+kGZII4XuJAoLyjq05n6hK9xu3L0X6iyPR6fI4HeqC8u
lcXSvcTyVvmOPdECOykYdwoW2O+ymiAJtbcpVgOs2i5aT4UYUkf2uCxW4uYUhsd1uYz/AFABq38n
uufwba+iteF5ZdLLpG1i5JhNOtrgf7rSEsU8YvkLIhe2ZjdQpw4KtMDmtsHZMVnh2fRJP4LWnegt
QG1g9DBOMxwdutqN+w1bLvPTz/qwkm7BOlk7TWyRdRTDlEhHseU6FraKJDUNahk5H5Ur+EBTIG0k
kks1HaiQtRJgpJJJJRJJJKRBOmSQpcOeFGeSnLkKCZ50hZnUJNitCUmisnPdYNJ/FJ5Yc1hxPypc
HNfG8sJ2KaVhcOFXdGWEOuqXDXpk8NpzQ8G1l5waL+Fcwsgysq1R6jbXOF8KMjOfMG9kzc8s2IUM
xbXKqSTNbsShuRenlbOCbWRnQOA2tXYqeLa7dV8sSg0eFFiPa9hXZfQOUfTdG510VzE8dklbH0k5
sOc4E0CqOfc8PSRxt4RKOEh0Yo3spF1npxEkhBToMoTyUtPyitOlAr5TJyEqRgD2KGkR4TKagTsh
seUTuEIArhFJNPP5Tpg2rToJ9R77oXNbICC0J07QkBhhEV0TSm7JBJLAXUonHndSu4VWeTQ00ENS
q2blMgYSXLm5sqWfIJshvi1q5DTLqLia8LJyTo3CxXp+LM8rbepsxoqBt3hVxPNlSl0gOnsFRZ75
bcVpQUGgBDVkTRbcjf4V3HdXJVOOlNHzymOd9L4KdQtdXypGuu90snUb9ijJ2UTjaiB/CjtFIVAX
bqRpTarE/KmeeVWed0GGc7dQvNcoyVBK7Z26i5f61yvTxdDTz/6rgTubXSfWOaZskRA7MXOs5XTi
eHk7vkm8BTRcqMo4vuWmZEylj2J/CjHKmiGolYdYsYhqRacfuBpZeNs8rSxyWndZbi9A86BXZaeL
IXxaX8eVlYxGrlacAqMhUP46z6fcP04byAt5rA5vF/8ARcz9NvthHyunjdbfwu/Pp5rPIWEiwSpW
nZREbo27JAxyiQpalAWpLUh1JalYtO54pByi7lIC0pspJJLFJ2okLUSYKSSSSUSSSSkSSSSkA8lJ
I8lN2WCilOxCx841a1ZyGsIWTmDY2teo1z7Z07zQAVd41BTyfKgeuD0RNi3H9qk6jE10Qf3IUWKD
vSlzXXDXgKMc3lwkE0s+UEmitiSntI7rJyLZIQQh0hY7nR3XbwmfOZAd/wC6ASU0gKH16d9tqAZZ
dyKVnpWT6eYxwNEuoqjlut18IsAEyavBTGa9Z6bKJcdpvkK2uf8ApzN9WBrCRYXQchbjz0k/ZMn7
JBDgp01J0NSYFJJJLICLTIkHdDUJDsiQqah0ySFHtacFEECccowaO0tQ7lATQO6iL9+U6cSncGiq
842Pwiad00jbBKFGZlkFh8rByg4yEFdFkR7HZY+VDR1UudejlnAb/hW8eXYC1Xc3S4p4+VStNJjh
2KmiO6oRS0TurkMgq06xV1rrCMGlA1wKNp5SwlLrUZOxT2o3uSYFx7qu672UrzsoHO2KEjcSoXnc
qVx5UBUYFxoKlnzCLHkeTWkWrTtxS536qzhj4UjP6uFLrw4bqmT6+ZI+7s7Ko0UR8pzbiXHukBS7
cx475pzwpI+yipSsBA2VY1EzeVPFsVE1uwUzW/ssVuLEYrdXYeFUby0AdlaYdLaWW4uY33LWgsxn
+yx8c1utbGP8FBdF9MurUPldUz7RXC476bkcyZ7fK62F1xr0c+nm69pHIkHZG1OCCApOkmseVaDp
JJilHTs5QjhE00pNhJJJYpO1EhaiTBSSSSSiSSSUiSSTIATyUyfTukRQWWlTKFmlmZjhYba08o8r
Jyxb1X01z7UJhRUJarUzbb+FCGgBcseiQUGloKGd4cxzfhOBSikFEo0xjPLo5XWeCqec31Pe0cLQ
6hEWPLxwVnTyBkR1KaUXGm/KquJBKtuIcCQOVWlbuowFersd1oYkIiZZ2Cq4bCXnbhTZU5YNN0mD
G59M9R9POLC+r4XexP1xh3leO4mS7HyGyt+5pXp3QOoNy8Vh1Wa3W3HuZWw3hEOENp0sCSSSU0SD
ujQ0gUKE8lOeCmUoSj0jwpEymgoUZBG6arRB7Cm1pzXhCQK4QZyB7qBVKSVwefwrcnCrPaCTsh15
5CzIdSmjlJFqu6P3Ig6hQQ6Xj+Fk7tNFZk42K05Kc0KtNE0g7Io5lY8zAAoWtFrQyMU1wqbmaTws
tmaFahFgKBrdlYh8JZsWWPoI/U+VGKBqknHlajFiXXsd0D3gjlQlxGwQ6r8JCQuruoidynLrUTza
kTzvyoXFE49lC88oagJHhoJK8++rOofqMkxtdYC7DrWaMXEc7VRpeaZUpyJ3vJskp5nly+TpCBz4
RN5SpIBdceeHIsUpGBALRtCmpZVuJuppFWQjaL2Q4vsdqPflShha8gN2WK3FnFaHA/CPygxiGHUd
r2TkW9xHFrLUXYjTWla8Drh+FjsGpgIWvhj+EhprdFJGTzsuvhf7W+FxvR3VKV12LvG0rvx6cO/a
2ia6kA2S1LeOfpLqCX7qPUnB5TkI7rukDaBEzgrOKUYT1taYcItPttQbCSSSyTtRIWokwUkkkkok
kklIkkkkAxNBRuPKMqN5oFDUVZTdrMyR71qSN2JWdljkrNb59qrgNJVV5PAUxdYKi7lcq7wItNI2
x+EZbSThyFlpQyYhJEQey57OYQx4O1cLppm6WnwsXPia8EbJhxkYw1NpDLGfFqzBiyNcfbspzjOP
8qSqY49ON5IVHIcXyklak0ZY0trt2WaYXanbFQ1H/LS6L6R62cWduO91NcdrXPOboBsqvHM6GRsj
TTmnalqMdR7dBIJGagdiFKD2XLfSXXW52IGvf72bEHuuna4OFgrTiNEhv5SCVKJCiTDsg0BbsmOw
UjuFE5RwvwmtV55XRh2kWaWPN1jJY7SMcn5Lla3xxeq3Hvrk7KI5TGXZWKeoZcrD/D0nxaz8qTPc
DTi38LF6ev4/8WX26U9RZwSAPJVaTrGKN3ZLG/lwXCZvSM/OcdfUZ2jw00qZ+k3NPuyJH/lZnbt/
4s5d/J1vEG4yWEflQjruGZC3128XzsuIb9MlgoSyhRS9BlD6E7/Cvs1z8F/Hf/6tivZqbMw+aKil
61hRNJOQwfuuDi+n5A+jM8jxasO6CNNFpI+Ss/ZqfF27AfUHTXbfro7/APEpWdRxZf8AbyWP/wDu
XBO6BFx6RpRO6Ixt6DI0+WuIR9j/AKK9BfkBw3OyryMjeSQaXGwNzsRo9PMlIHYutSHq/VGH7g/8
p1nr4cdUWhopptHDz2XHHr3VAd2MVvpvVOoSTapQwN8BLzd/HY68OF8Jnd1Xx8gyMDnbEqfUCEyu
FRnkoURq9k3ZagN2UZO6J3CjcpBduCq73hoNqZxFHdYf1B1FuHjP0uGqkG+Jrm/qzqWt/oMdYC5g
d1PkTHJldI7c2oiF14jy3raZE0bUmDSeFK2HaytaMM1qlZHdJMYAOFKwgCqWbWpBc2B2VnHJfbTy
FXbRU8Vh1jss1uRK7YaT5TwOuwU726/c0b+PCaNuk3VLJXoq0rVxHkQrIx/dstXF/wBtTTT6V/uk
Lr8M/wANo+FxvTCf1Gy63DJ0g/C7cuHye16/lK/lAN0jstY46kvakmmkF/KQ3S0l1fhE11BQg0VI
3hWJOCnvakDTaMKxNlJIb3SVLBO1EmanTBSSSSSiSSSUiSSSUguUbuCpHKN/BWIYgf8AaVn5Tbv8
K+/g7qnOLKK3zfLKO1hRsNlSzgiyFXiduuTvE4Zd2hLNlIO6F3CPq1FaZttIWHnN0vW5IaJCyOps
ogpKpG/T8qQ5DWNJc1Qxt1eU2Q2oyoquTms1bClXdkagSAocpwDxwjhaHsdwplUmc4klVZHK7PHp
JCz8iw5MZvpe6L1SXp+ex7SdBO4XrfRs5mZitkB5HC8UgH8Zv5Xpv0tI5uMwArWueOvHBRDhRxP1
M53rdSDhMZOOEh2SHCQ7JP8ACdwoipSLCCkFCYweQqOXhtdbgFqgCuEBjDhuUY6c93lhCIN2Dd0M
sH8PazutSXGGokKExgbEI+sevj5WS+FrDpIsqN8I32WnLjhzy7wFEMewbHKx9Y9k+XWY6IeB/ZQP
hZfAWg6KtYruoJ4tLQQSs2O3HeqrIGcgWjkhDW2BspIG24qUs1eqPBR9R11lZj4W6Sq74WrRliNb
KsYXkcbK+sM6ZxjFqGVluNrQfBZ2QOxw4cbpkZ76ZzcZpd3K0MPGaALCPHwSXWRQ/CutgDAAp4fk
684eO2muArDXbbqMNA4CcWCp575S87piavdMChc5MYM51qJzkRcKUEr2taXONAd1qJFl5IhjcXcA
Lzz6g6m7NyntBOkLX+puuCQuhidt8LlHEklajl13+AArYJqBRcJAg8LpL4csg4Y7UwaLQQ7D9lJq
HdGNYVBOExP4TsCMMSxR+VZYABsq8Vk1vSstFBZrpDsOk/lTemCLHCgtWYj/AAyLQTwOLH/C2Mc0
zZZDNnD8rXiFNAvsoRd6a6skBdhhbxBcb07fIC7HCb/Cau3Dj37W2pz4TNCVbro5yF+6cbJUUgE+
Cc8KSMbIK2Rx7BQTN4RDYIWcFEFei2mjlOUwvslRXE74O1EhbtaJajJJJJJRJJJKRJJjaa9yjUTl
FIdqUp4tQycohiBwJtVcgaVdA53tVMsC+Vmxrn2y5z7SqjB7lblGxVce0G1yeiJQbCF5oIBO0WlJ
K10ZIKmop5s2h2ypTSNmbTjuFJnEFwNqkXt3oqaAxlE6UGSKjNhHr0uCHqD2+lt4UKwMoFzjQ4Sg
c+MbnlDI/wBx35KCd5awEKZTSu1i7VORocCVC7LJ9pKFz7GxSKeL2yt/K9I+ljeO0/heaRH+K0fK
9L+lf+zN/ZLDq4jpJVhrrVVu4U0Zo0tQWJgnHZC0hEEsyHTUO6dMd0Nbhk3ZINKdK9oy0Vwo5IgR
wpihcsqWxUMA35QPhbXdXCAVG+MHkrLtz8lZskI1Eqq+AkEEbLVfCzyozAwjdyMen4/nnPtlx42l
1hEYtOo19y0hBH5TPx2OFWrG7/kc1kPiobKB0LyCAFtjAYeXJ/0kcYPdQv8AlX8YcWAXbkKQdPa0
8UtVwa3hoCrvNkrOOXXy9dKjoQxtBQOZyrchG6rP5KmNv6jqkxI5Sc6tkLtiUAi/dA4/KawLNoHv
B7pR3OAC5j6m667HjfFEQSdlb6/1luDjODHe/wAWuDyciTKldJISdXytcxy7uB1uleXPNkovT7gI
WNLjQU4OkUV0jl7VXMN1SHRXAVvS07qMt34WlgIwapS6RXlMG0iaO1o1G0hSsj9oTMYC5WmNWaYU
DCL9qkdx8qUOAZXdRlus8rLYG7HdMJSXUiMbuyTYnd1JYx36jTuVtwe6EVuVhRMLT5W7h22IKhi1
05pGULXaYTf4TfwuS6c1rslp7rr8PdgA8Ltw49+1gDYpqRhuyfT8Lr4cwUU4byi0pw1WozW7IgKR
NCctQjs4RDhC0UEQ4RaW4zuir4QN7oliLSKSSSWSSSSSSSSSUjITyUSE8lY/VDXsoX7kqVyiO6SH
gGlSyTyrch0tKqvj9Ru+6rNMuVnSCgVSmeGiitCcaSQVl5e26416OfKJ7tuU0Uu9eVH6gO1qFz6d
sh0xH1AFribWW+Uh3K1Mt4eAD4WZPECDpU1DsfqFlBlBzo3V2CihdodpcVbIa6M13UK5qSQiQg9i
lPM0xht7qbqGN6cpdWx7rMzLDNTVOdoJWAk6Tuoi9zNlFHORd7ozMH8hakY1LiuLp2X5XqP0uC3G
bY8LzXpkXrZDa3or1L6fi0YzduwUcdEzgoxsgjHNo6TowbHbqUHblQBG1ypRUyYJgbThI9nQokKW
oE8lCQKRHkoTyhkJ4UD3FTGwonb9ljGogeHEkgqM3asObyo6CsbiO6KcO53RFqAirQRCQUhLrCAp
kHAyOo8qs9wPypZDuqr3UUGBkdsq0rtlLI9VZH8hRC6QWgLib3TEhA5xHClgiaWd1HqDMWI+4kqX
LyBG0m1nDo+d1iKSeJlMGw+UyaL4cj1LIkysgukcTfYqqIj2FrvX/wD8dGbE1iZwmq9xsuY6h9Od
S6dKWHHfJ4LByukjhbtZkTtGxajLQ/8A9Vp43091TKArBe2+7hSDqHQc3pwuaOm9z2C1F4Z2g8Dd
ExupwbRJ+F0X0z9GZHXIzkPkMMF0Nt3Lqel/REHTMp/v/UXxqHCWbXm5xb5BH5SZA1p3Xon1B9Gu
zWA4gDJO9Bc9lfRHUsWHWHtkcOWgLONc455kYBtTAUeVfH0/1ECziP2VOWF8T9MjaIWa3MQucbO6
djiAn0i07m0NkRHEwPKNtPHtNqpwSpIiRwVMrkbHA2Ft4xJhAIWLivN0Vt428aY1F7pL7yK8LscF
vsC4vo//AGwrtsL7B+F14ce/a0AlScCyjDRS3HMFJwEWn5KelrVhmik5GycJALJMnHCRCQCLE229
0SYCrTogJJJJKJJJJSJJJJSMhPJRITyVn9UC5RdypH8KNP4UcqDSpHN1IapUiZmWz3FZeYzYrZyw
dys3JbYXOx2+NguJjeR8oHm7IKs5kXJAVQAgFYsd+UMz7B3VV59vKkkdTiFC93KG1B0rmzkHgLSh
naWAFZco/il1o/XIbQ3UM8JuoRtmZQIvsudz4jHE8biitieb2AkqLKiZlYzgOaTHLqeHKg0Tuk1z
mkAEm0c0LoZC0hWOnYbsqdoA2C3fTly6D6XwTJIHkL03pUGiIdtlzX0701sELSWG11+KzSwBYdFu
Pgo0EY9qMBIOEgUq+UggDa6kYcDyouyIELcGJK+SlQSBFJ1INBARuUdb8oVDUZFqMt5UpCAhGFEW
oC0KatioyENc1HpKBw5Up2BQEWjGkJHIQnYI3CigfwjDqCTcqo/lWpOVUlcA5Za1XmNk7qs83spn
n7iqrjuowxdSgmnDBZRPeN96/dafSOhDJDcjJbbXfa1MlotxzUjZMt4axjpCTwwXS7zoOEMbpzId
BaPuojdS4/TsfDFQQtbZ5rdXMcaWUSTW266cx5/k60xha263CrTYcUjrdGD+yuPNoB3W8cp4QR4s
bNg0V4pVs3pONmxujlYHA9iFofykoSLUdVsPCiwsdsMTQ1rBsAFM1m6Lsk1Uo/S0hA6JjhRaFJSa
wtHUTsaPSfbyF5r9Z9Pbj5jZGCtRN0vTyaC5z6i6F/qkTi11OHGyx1HTivL9FO3Ucj9ytPqXTZsG
QxytrsHBZUg/8lzdKGrPypoxSijFHm1MFBcxBsbWxinYDssrFbYFLXxgRSp5K505tZdjyu2w/wDb
b+FxHTxeaB8ruMIexv4Xbhx79rTfKNAwXaPTtytxg9fKVfKdJQNSdMDadSJJJJSbiSSSyiSSSSiS
SSUiSSSUiQHuiJoIeyyoieShq0ThbkxFDZUIa2TEI6NIaSYp5LNisnJ2dRW5M27WR1GL22OQs1ri
2MyeMOad1nuj9xV6V225VcgEu/C516ZWJkN/jO3VPIm07LTnjBJcAsTqZ0zcrLSCWYXfKTJAfKqS
vFqEZhY7mt1DV7Kd/BIPZQ4+RtWpKSX1oXEbmlTwY3yyEVW6mKsOxRmPpvNre6F0EwuDiB/ZD0fp
vutw7rsMDEDWt24Tq+si10/GDGBacYpRRRhrapTMFFEX4mj+1GCOAhZ9qJoWmKJJJJCLsmGydMN1
qVQQdspGm28qIJwaTAkTVsmDtkr+VM4YhBXKkUZNWgh2oqJG51XSjvlGNwLuChrYlHVhASAENRG8
KGRSSO3pQua48DZS1XlNXuqUx3VuiZw072VrDDgLQ0xA+dkTi1ffHKhsmRII4xZWj03opfMXZLQW
+FrR9Ogim1sYArjYwNwFucY535NZc30/hSHaJorwrkeP6UTWt4aKVkMu9k4Ye63OY53q1C2N1fCO
tI2UmkDugJ5UyjceyEd05FlOG7FUQe1JiE6VJQaT0jaywn0BWJEo+CpiFGWm1InCwCoy27Um9Ji1
S1gdf6DH1CA6WgHyvN+qdGyMGVwcw6AdnVyvZC0EFUsvpMGWwiRgPwsWNzp42xmkb/4RLpvqH6Yd
hPdNAw+nzQWA1tk+As46TytYg43WrjEv2aCT4AVLAxjNNHE0e55oBeg9M6Jj4mOG6dTjy4hakVuO
X6fBM3JDnRua3yQu2wv9sfAVPIwi/IZpFNHhaEEfpsorpz4crdTx91Ko4xyjB7LTJ0kklAyKtkyL
sUIKSVJJTcSQ6ktSxqwSSYG06QSSSSSSSSSkYiwfhDe1IuyFZUAeQmpO4f4TN3tMaI8FAVIRsgLV
D9RvFtKo5UQLXbK+eCoZWAj9kYXJZ7DG4/lVGyindzS3epYuppobrnHAxSPa5Ysdvj6/qB0zacCs
XqLWuZZ5Cm6hk+iSL3WfLMZ4yAVh31mZDqtUZCX7gd1pnGc87tKlxukGWT7dkM0/SsZ8oDa7re6X
0enElgVjo3R/TIJZ8ro8TCDf5aChitgdPDTelbOPCGtoCk0UIaKGwVmNtAlQG0bI2hCzcFSMFlMj
OjHFIwgCK04zPIkkkkE1fKQTphspFaSakq+StYhJtdJuEx4JRBh9eyEu53Qk7IDwlSHLuyjcmaS5
1WiyI3NjsblUOhvndBe/NoIoJZAeymx8Rwfbyn2NJkGsgkKWWJrIzTRsrIaGighe3UCPKvqL0wIX
X1AgjYcLeib/AAwfKjZhsa8u0C1Zaym0mRm3UZYK2pEG0EYbdpFtBaY0NJUnSUtRu2tRlSuCjViM
AnrZOm7qSNwJtJrVJSaqUiA2T0nTKQC1AWqYoDSkjpKk5pMTSkAgboCLCMnlAsiK2Vix5MRje0Fp
C5jK+ioWyucHGj2C7ENSLb5NqdJfDmOjfTMWLkes8lxH2/C6WNoaAKT6a3qk7pGsG54WoNEGtG/K
Y0Sqv6oySFoOynZumBIzuk517JUADum28pZOx1GrUgKgJQiQ3ylLSQcoA8kco4juVJK4itkySVe2
0Jspk6SyTtRIASEgT5VKMGkmabCdIJJJJJMhRIVn9UCQhAo/lGhITCRSLbCQ3SJpS9gc1RubYU6B
/CmlDIg1DcLn+q9OvU5raK6mT7VnZrA5h2QY81zunvlldY4KWL0d1fausk6c0yE13Rx4IaeAuVd5
XPRdE0/yjdWounMjeKAW6cUBvZReg0G6FoMpYWPpbstCNuyhxmENVtjd91K07WUpQNimDbRtGymZ
SaKCkYgCNo2J8JZo06Fu4RKUEkkkhEkmTWnFh/Ka0kk6TV8lCSdwncSOCgtGgigJpEVGSSEzyhwM
Dn8K5oDm0QocSOmklWQNkudvkDI2ixSRZ8KQDdIhLOIqSARkc1ygHdalJ2jdEEwPZJvdCgwKTOTg
7JEWkWIwkn0pVsqWDKAoHDupEJFgqSNLunoplI6ZOkpBJpMHWnPBQHYKRy75QEpJncKRakJOyZIb
o0aakmjdFp+UgKVhmlSfSnATk7Kw6jcNiqOfqa00dyrz+FE5rX8i1JTwIHgW7ur4YUzGtHG1I3Ha
loajLqtBrTSHlCwElSHqKcMvlEBSV0lYcbDdSQ1uqznqXGdbqTqWAnAtqVJxsKQGukkkskkgkkBa
kdnCJMBQTpgJJJJKJDp+U6a1lQ1ISERPdAXBUMNdJF1oHPUTpgPhKidz9KhfJtyoJMihzaryTOIN
FGlPLPQ8qjK8ybA0n3dyUgwb91m105iARjwn0fsp9NJtNrDcVnMNHdQllbK65qryiiVlCxxTSPlW
WilXxq4Vprd+Uwnb3RN7oQKBRN/5VBPQqRA0KTBIKZSN4Tpm7bJ0mCSQ2laFhWkkg1lKL/7kv/uQ
pK0YcnsmOySY8IUMUA/CIkg8o4GiSQbcFakVWsdpazcKStk44pL4WsrnTDlI8lNdFODaF+BPKW6e
rSpKCBSTe6IplKQQ4ToQeyc7LURVaGt0QSrlFiR9ympSFoTaNuU/jKItpAQpeyHShYBJLSUqpSwx
FilG4dlIgdyoBqkyLdPpsKiRabS00pQ2ktKsKIAp6RVSakqUhwmKcISpI3WUKNwQKhIGktSbsUJO
yVgXblFGEPdE00FQCc4NCic+0zjZKB23dJNZcfyrmLEWDUVHjQBx1XsrezR8KZGkhD7S1KxNlJJJ
ZJJ2d0yQNKgGkh1FLUnVh73pK0J8oDIAELEln4QOeGqB+R8qF2R8qMiw7IAHChdkAdlWfNYURkvh
GtSLLsg0VXfKXWgr5SARpnJqJ7pVtSJNSNbwwanA2KIAVSIChSygtbYS0bIwkk4hIVeZvKuObsVX
nbbSsqIcf2vVscqgDTgbVyJ2pqm4lRAbIQLRBUBwnTJ1MjYbtEo2u0qRKhJIC8gpaypaWs/CFJJA
JJNfwko4fshtImgg5CUTjRVnEZpBJ7qoN3DvurrTQoFajPSw1OeSmj3pORRK3HMJ5KQSI5TArJEk
mtIbqRFMnq0tPyrEZvKclICk9WtT0ibwnTAUnUiTHgpEprUojPCZHp+UHCoJDGkgAmcLpO3wggPJ
QO5UhbVm0JFpZCAnCeklIySRKYqhNtSE8cp625QqZJCeUSEqhMeFGe6N3dRlBMeEB4RE9k1bcq0/
gQEjsCiBrwhJu6WpWcRuHe0LjYRONA8KF08TAdcgFeVSwrmFMK0EUeymmfpidvuueyPqLFwy97Tq
DBuVmYv13D1HK/TyxGLf2vJ2cs/Zl2mFRgBbue6sE7fKzOi5jJxM2NwdoO60SRe63E2UkJeAgL7W
SkSJpQul0g2VA7I53UVsyNA5Ub8gAbKg7INndRulc5CkXH5O3KhORfdVy5ztiUwsBRkG6YnhBqPl
Kkq3Q1hC6pIBOkhrCSTJ0okkklEXG6JR3siDrCzRPAh3STAp1fhhiLFKOQbHZG40EBNikJRlFOPZ
T47hxaCcC+EEbg14Q1KvhEFG19i0bTYVFRJWmSBSBJ9R8oQaT/uoYSSSSASa67pnGrUd2kiL/CbW
fhAXUEOr5CkkJtDqUZceLTX8oUWIKL96VoClnwEiQbrQ/l/ZbjPXtYidtfhETZUGOdqU63GDeUKJ
CsqEnBpMeNkzTdqIgU9oUkyjBE0m1JkLh3tSSDcJ0DXGk+pOo9JiE43SKlAoCNyjTEWURASRVym4
SNA87IUThaBQOmPCVoS40pQxKYmk1bpEUhYe9kKV7UmJUpDF1IdW6FzuUOpCwTnbFATskge6rCiR
eAo3SbUhc7ZROPygpPUpZvVOoSYzNUb6KtErM6uwviurUGPN1fNnupSB8KrqnNyTZDtPeyie9sVl
2wHK57q3Wn5Mgx8cu0k1+VBL1TqonecbHfqB2Nd0fRukS5c9NbZbu4hS9I+lc3IGr0zECbLnf9F3
PS+mRdPgETG0Rye5KoE309AemxhjiSXG3Fa2VIHvtjjQ2VKNlPCsadqWom87KaFE/JFbKpR8pUVa
6/SJTM9wO6EOJtCLCcGuytX1P333SaSeaTWkDSpTh3JkibSRTCTJ0yEbUnFpUE6iHUbpLV8JEb2m
q1IXZJNfZK0asOkE1pWhYMGh+E+seFGCnsJ2ITtwhStJFCKRmppPwqbgQ6/CvndpCo5DCLKG4tQP
1NCnbys/Ek3olXmnZQqS026FLVaVo2/bacOQF17KSGF0hv8AlCozQ38hOFYMDHNJaKKhe0s52Til
RvO1WgJTu7qN3CFoSbQpEoWm1NSHStDYvlO0FztIFokSTG3l/C0Cdvyq2NimNxc47lWm7jytxzo4
FOoI9ipgbWoydMQkklBpMBuUV2EyySSSSUiTO4TpiLCoib9qdMBQpOpCCRTA0EiVoGSSQWsyI/AK
G0rTavhaEhnGlGicUKoi8pimvdMXItPoxNFCX32SJpCjQK1G53KdzgFCXKtROKAn5TF25TErKPqQ
PcntROdypGJtRuREoHeVEJ4WN9S5T8TDL4+R28rZdwQqmdgsy2aXjUEh5rk9Sy+qD0ooHOJNU0Ld
+lvpX0p2ZOa3f+Vh7LpoOmY+K0NjhaK42U7GhrgR2PZAXA3SO3/knaB2UYII3KNpFJSWNu9o1E07
UjtaMjUSQ2lazrtgkkLUSgSSaxdJtQUhJJgbFp1I1prTlMEmHG6INsJm7fKNu6ECt6S0nwpdKWlC
QEIXAnhTlo8KMtRiQ78WisgbIi3bhAW90YYcE90+pRlJtoOJAU9qOyAU4O25Vqw6inbqBHwpAT8J
n1pKkz2kxvKvwya2WqmRHW4CWNOGnTak0E2oXSEPBCYGimDEgN7NFlWIfXYCNFhBiyxtO7RqV9pJ
F0tRztRNmp2l/tPhPKwPbVBFIxrxZ5HBQDikjVORuk0onXWwV98YeKP+FH+hYeXFEilZriapALOw
Wi/pzSNiQhhwPSO5v8qxudKbIHuNUtDGxREPduSpmxhvApF2SxetDVJwkU26vQECpGOvZVwKKNtq
Se0yFpsJB3ZWqDCR5KQ4TJUJJK0lEkkklIr3pJNW9p1I/ZN2SJ2QA8/KfYPr+EKSa0+kYpiaSJoK
Mu8lZRE8ptWyHUEGolWoVpiUKEupGjBJiaQF1oS75VERO5KicbKTnUTuo3O+VWkRKAuTFyAu2Kxq
E52yC0OpNqHlUawW9ISdkxcCEJNApZwqvlOBsog82jBWokcjC5C2MgqxyCm0/CgBoUoFCkOwGwUU
2SI28qSyCK5UbskN2sLOdnizuqmVmaTYKzof/9k=</pkg:binaryData></pkg:part><pkg:part pkg:name="/word/settings.xml" pkg:contentType="application/vnd.openxmlformats-officedocument.wordprocessingml.settings+xml"><pkg:xmlData><w:settings xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:m="http://schemas.openxmlformats.org/officeDocument/2006/math" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w10="urn:schemas-microsoft-com:office:word" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" xmlns:sl="http://schemas.openxmlformats.org/schemaLibrary/2006/main"><w:zoom w:percent="100"/><w:bordersDoNotSurroundHeader/><w:bordersDoNotSurroundFooter/><w:defaultTabStop w:val="420"/><w:drawingGridVerticalSpacing w:val="156"/><w:displayHorizontalDrawingGridEvery w:val="0"/><w:displayVerticalDrawingGridEvery w:val="2"/><w:characterSpacingControl w:val="compressPunctuation"/><w:hdrShapeDefaults><o:shapedefaults v:ext="edit" spidmax="3074"/></w:hdrShapeDefaults><w:footnotePr><w:footnote w:id="0"/><w:footnote w:id="1"/></w:footnotePr><w:endnotePr><w:endnote w:id="0"/><w:endnote w:id="1"/></w:endnotePr><w:compat><w:spaceForUL/><w:balanceSingleByteDoubleByteWidth/><w:doNotLeaveBackslashAlone/><w:ulTrailSpace/><w:doNotExpandShiftReturn/><w:adjustLineHeightInTable/><w:useFELayout/></w:compat><w:rsids><w:rsidRoot w:val="008D401F"/><w:rsid w:val="003B578C"/><w:rsid w:val="00490FD6"/><w:rsid w:val="008D401F"/><w:rsid w:val="009C09D5"/><w:rsid w:val="00A14B3E"/></w:rsids><m:mathPr><m:mathFont m:val="Cambria Math"/><m:brkBin m:val="before"/><m:brkBinSub m:val="--"/><m:smallFrac m:val="off"/><m:dispDef/><m:lMargin m:val="0"/><m:rMargin m:val="0"/><m:defJc m:val="centerGroup"/><m:wrapIndent m:val="1440"/><m:intLim m:val="subSup"/><m:naryLim m:val="undOvr"/></m:mathPr><w:themeFontLang w:val="en-US" w:eastAsia="zh-CN"/><w:clrSchemeMapping w:bg1="light1" w:t1="dark1" w:bg2="light2" w:t2="dark2" w:accent1="accent1" w:accent2="accent2" w:accent3="accent3" w:accent4="accent4" w:accent5="accent5" w:accent6="accent6" w:hyperlink="hyperlink" w:followedHyperlink="followedHyperlink"/><w:shapeDefaults><o:shapedefaults v:ext="edit" spidmax="3074"/><o:shapelayout v:ext="edit"><o:idmap v:ext="edit" data="2"/></o:shapelayout></w:shapeDefaults><w:decimalSymbol w:val="."/><w:listSeparator w:val=","/></w:settings></pkg:xmlData></pkg:part><pkg:part pkg:name="/word/fontTable.xml" pkg:contentType="application/vnd.openxmlformats-officedocument.wordprocessingml.fontTable+xml"><pkg:xmlData><w:fonts xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:font w:name="Calibri"><w:panose1 w:val="020F0502020204030204"/><w:charset w:val="00"/><w:family w:val="swiss"/><w:pitch w:val="variable"/><w:sig w:usb0="E0002AFF" w:usb1="C000247B" w:usb2="00000009" w:usb3="00000000" w:csb0="000001FF" w:csb1="00000000"/></w:font><w:font w:name="宋体"><w:altName w:val="SimSun"/><w:panose1 w:val="02010600030101010101"/><w:charset w:val="86"/><w:family w:val="auto"/><w:pitch w:val="variable"/><w:sig w:usb0="00000003" w:usb1="288F0000" w:usb2="00000016" w:usb3="00000000" w:csb0="00040001" w:csb1="00000000"/></w:font><w:font w:name="Times New Roman"><w:panose1 w:val="02020603050405020304"/><w:charset w:val="00"/><w:family w:val="roman"/><w:pitch w:val="variable"/><w:sig w:usb0="E0002EFF" w:usb1="C000785B" w:usb2="00000009" w:usb3="00000000" w:csb0="000001FF" w:csb1="00000000"/></w:font><w:font w:name="Cambria"><w:panose1 w:val="02040503050406030204"/><w:charset w:val="00"/><w:family w:val="roman"/><w:pitch w:val="variable"/><w:sig w:usb0="E00006FF" w:usb1="420024FF" w:usb2="02000000" w:usb3="00000000" w:csb0="0000019F" w:csb1="00000000"/></w:font></w:fonts></pkg:xmlData></pkg:part><pkg:part pkg:name="/word/webSettings.xml" pkg:contentType="application/vnd.openxmlformats-officedocument.wordprocessingml.webSettings+xml"><pkg:xmlData><w:webSettings xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:divs><w:div w:id="394471120"><w:bodyDiv w:val="1"/><w:marLeft w:val="0"/><w:marRight w:val="0"/><w:marTop w:val="0"/><w:marBottom w:val="0"/><w:divBdr><w:top w:val="none" w:sz="0" w:space="0" w:color="auto"/><w:left w:val="none" w:sz="0" w:space="0" w:color="auto"/><w:bottom w:val="none" w:sz="0" w:space="0" w:color="auto"/><w:right w:val="none" w:sz="0" w:space="0" w:color="auto"/></w:divBdr></w:div></w:divs><w:optimizeForBrowser/></w:webSettings></pkg:xmlData></pkg:part><pkg:part pkg:name="/docProps/app.xml" pkg:contentType="application/vnd.openxmlformats-officedocument.extended-properties+xml" pkg:padding="256"><pkg:xmlData><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties" xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes"><Template>Normal.dotm</Template><TotalTime>2</TotalTime><Pages>1</Pages><Words>11</Words><Characters>64</Characters><Application>Microsoft Office Word</Application><DocSecurity>0</DocSecurity><Lines>1</Lines><Paragraphs>1</Paragraphs><ScaleCrop>false</ScaleCrop><Company/><LinksUpToDate>false</LinksUpToDate><CharactersWithSpaces>74</CharactersWithSpaces><SharedDoc>false</SharedDoc><HyperlinksChanged>false</HyperlinksChanged><AppVersion>12.0000</AppVersion></Properties></pkg:xmlData></pkg:part><pkg:part pkg:name="/word/styles.xml" pkg:contentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"><pkg:xmlData><w:styles xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:asciiTheme="minorHAnsi" w:eastAsiaTheme="minorEastAsia" w:hAnsiTheme="minorHAnsi" w:cstheme="minorBidi"/><w:kern w:val="2"/><w:sz w:val="21"/><w:szCs w:val="22"/><w:lang w:val="en-US" w:eastAsia="zh-CN" w:bidi="ar-SA"/></w:rPr></w:rPrDefault><w:pPrDefault/></w:docDefaults><w:latentStyles w:defLockedState="0" w:defUIPriority="99" w:defSemiHidden="1" w:defUnhideWhenUsed="1" w:defQFormat="0" w:count="267"><w:lsdException w:name="Normal" w:semiHidden="0" w:uiPriority="0" w:unhideWhenUsed="0" w:qFormat="1"/><w:lsdException w:name="heading 1" w:semiHidden="0" w:uiPriority="9" w:unhideWhenUsed="0" w:qFormat="1"/><w:lsdException w:name="heading 2" w:uiPriority="9" w:qFormat="1"/><w:lsdException w:name="heading 3" w:uiPriority="9" w:qFormat="1"/><w:lsdException w:name="heading 4" w:uiPriority="9" w:qFormat="1"/><w:lsdException w:name="heading 5" w:uiPriority="9" w:qFormat="1"/><w:lsdException w:name="heading 6" w:uiPriority="9" w:qFormat="1"/><w:lsdException w:name="heading 7" w:uiPriority="9" w:qFormat="1"/><w:lsdException w:name="heading 8" w:uiPriority="9" w:qFormat="1"/><w:lsdException w:name="heading 9" w:uiPriority="9" w:qFormat="1"/><w:lsdException w:name="toc 1" w:uiPriority="39"/><w:lsdException w:name="toc 2" w:uiPriority="39"/><w:lsdException w:name="toc 3" w:uiPriority="39"/><w:lsdException w:name="toc 4" w:uiPriority="39"/><w:lsdException w:name="toc 5" w:uiPriority="39"/><w:lsdException w:name="toc 6" w:uiPriority="39"/><w:lsdException w:name="toc 7" w:uiPriority="39"/><w:lsdException w:name="toc 8" w:uiPriority="39"/><w:lsdException w:name="toc 9" w:uiPriority="39"/><w:lsdException w:name="caption" w:uiPriority="35" w:qFormat="1"/><w:lsdException w:name="Title" w:semiHidden="0" w:uiPriority="10" w:unhideWhenUsed="0" w:qFormat="1"/><w:lsdException w:name="Default Paragraph Font" w:uiPriority="1"/><w:lsdException w:name="Subtitle" w:semiHidden="0" w:uiPriority="11" w:unhideWhenUsed="0" w:qFormat="1"/><w:lsdException w:name="Strong" w:semiHidden="0" w:uiPriority="22" w:unhideWhenUsed="0" w:qFormat="1"/><w:lsdException w:name="Emphasis" w:semiHidden="0" w:uiPriority="20" w:unhideWhenUsed="0" w:qFormat="1"/><w:lsdException w:name="Table Grid" w:semiHidden="0" w:uiPriority="59" w:unhideWhenUsed="0"/><w:lsdException w:name="Placeholder Text" w:unhideWhenUsed="0"/><w:lsdException w:name="No Spacing" w:semiHidden="0" w:uiPriority="1" w:unhideWhenUsed="0" w:qFormat="1"/><w:lsdException w:name="Light Shading" w:semiHidden="0" w:uiPriority="60" w:unhideWhenUsed="0"/><w:lsdException w:name="Light List" w:semiHidden="0" w:uiPriority="61" w:unhideWhenUsed="0"/><w:lsdException w:name="Light Grid" w:semiHidden="0" w:uiPriority="62" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Shading 1" w:semiHidden="0" w:uiPriority="63" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Shading 2" w:semiHidden="0" w:uiPriority="64" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium List 1" w:semiHidden="0" w:uiPriority="65" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium List 2" w:semiHidden="0" w:uiPriority="66" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Grid 1" w:semiHidden="0" w:uiPriority="67" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Grid 2" w:semiHidden="0" w:uiPriority="68" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Grid 3" w:semiHidden="0" w:uiPriority="69" w:unhideWhenUsed="0"/><w:lsdException w:name="Dark List" w:semiHidden="0" w:uiPriority="70" w:unhideWhenUsed="0"/><w:lsdException w:name="Colorful Shading" w:semiHidden="0" w:uiPriority="71" w:unhideWhenUsed="0"/><w:lsdException w:name="Colorful List" w:semiHidden="0" w:uiPriority="72" w:unhideWhenUsed="0"/><w:lsdException w:name="Colorful Grid" w:semiHidden="0" w:uiPriority="73" w:unhideWhenUsed="0"/><w:lsdException w:name="Light Shading Accent 1" w:semiHidden="0" w:uiPriority="60" w:unhideWhenUsed="0"/><w:lsdException w:name="Light List Accent 1" w:semiHidden="0" w:uiPriority="61" w:unhideWhenUsed="0"/><w:lsdException w:name="Light Grid Accent 1" w:semiHidden="0" w:uiPriority="62" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Shading 1 Accent 1" w:semiHidden="0" w:uiPriority="63" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Shading 2 Accent 1" w:semiHidden="0" w:uiPriority="64" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium List 1 Accent 1" w:semiHidden="0" w:uiPriority="65" w:unhideWhenUsed="0"/><w:lsdException w:name="Revision" w:unhideWhenUsed="0"/><w:lsdException w:name="List Paragraph" w:semiHidden="0" w:uiPriority="34" w:unhideWhenUsed="0" w:qFormat="1"/><w:lsdException w:name="Quote" w:semiHidden="0" w:uiPriority="29" w:unhideWhenUsed="0" w:qFormat="1"/><w:lsdException w:name="Intense Quote" w:semiHidden="0" w:uiPriority="30" w:unhideWhenUsed="0" w:qFormat="1"/><w:lsdException w:name="Medium List 2 Accent 1" w:semiHidden="0" w:uiPriority="66" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Grid 1 Accent 1" w:semiHidden="0" w:uiPriority="67" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Grid 2 Accent 1" w:semiHidden="0" w:uiPriority="68" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Grid 3 Accent 1" w:semiHidden="0" w:uiPriority="69" w:unhideWhenUsed="0"/><w:lsdException w:name="Dark List Accent 1" w:semiHidden="0" w:uiPriority="70" w:unhideWhenUsed="0"/><w:lsdException w:name="Colorful Shading Accent 1" w:semiHidden="0" w:uiPriority="71" w:unhideWhenUsed="0"/><w:lsdException w:name="Colorful List Accent 1" w:semiHidden="0" w:uiPriority="72" w:unhideWhenUsed="0"/><w:lsdException w:name="Colorful Grid Accent 1" w:semiHidden="0" w:uiPriority="73" w:unhideWhenUsed="0"/><w:lsdException w:name="Light Shading Accent 2" w:semiHidden="0" w:uiPriority="60" w:unhideWhenUsed="0"/><w:lsdException w:name="Light List Accent 2" w:semiHidden="0" w:uiPriority="61" w:unhideWhenUsed="0"/><w:lsdException w:name="Light Grid Accent 2" w:semiHidden="0" w:uiPriority="62" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Shading 1 Accent 2" w:semiHidden="0" w:uiPriority="63" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Shading 2 Accent 2" w:semiHidden="0" w:uiPriority="64" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium List 1 Accent 2" w:semiHidden="0" w:uiPriority="65" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium List 2 Accent 2" w:semiHidden="0" w:uiPriority="66" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Grid 1 Accent 2" w:semiHidden="0" w:uiPriority="67" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Grid 2 Accent 2" w:semiHidden="0" w:uiPriority="68" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Grid 3 Accent 2" w:semiHidden="0" w:uiPriority="69" w:unhideWhenUsed="0"/><w:lsdException w:name="Dark List Accent 2" w:semiHidden="0" w:uiPriority="70" w:unhideWhenUsed="0"/><w:lsdException w:name="Colorful Shading Accent 2" w:semiHidden="0" w:uiPriority="71" w:unhideWhenUsed="0"/><w:lsdException w:name="Colorful List Accent 2" w:semiHidden="0" w:uiPriority="72" w:unhideWhenUsed="0"/><w:lsdException w:name="Colorful Grid Accent 2" w:semiHidden="0" w:uiPriority="73" w:unhideWhenUsed="0"/><w:lsdException w:name="Light Shading Accent 3" w:semiHidden="0" w:uiPriority="60" w:unhideWhenUsed="0"/><w:lsdException w:name="Light List Accent 3" w:semiHidden="0" w:uiPriority="61" w:unhideWhenUsed="0"/><w:lsdException w:name="Light Grid Accent 3" w:semiHidden="0" w:uiPriority="62" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Shading 1 Accent 3" w:semiHidden="0" w:uiPriority="63" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Shading 2 Accent 3" w:semiHidden="0" w:uiPriority="64" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium List 1 Accent 3" w:semiHidden="0" w:uiPriority="65" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium List 2 Accent 3" w:semiHidden="0" w:uiPriority="66" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Grid 1 Accent 3" w:semiHidden="0" w:uiPriority="67" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Grid 2 Accent 3" w:semiHidden="0" w:uiPriority="68" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Grid 3 Accent 3" w:semiHidden="0" w:uiPriority="69" w:unhideWhenUsed="0"/><w:lsdException w:name="Dark List Accent 3" w:semiHidden="0" w:uiPriority="70" w:unhideWhenUsed="0"/><w:lsdException w:name="Colorful Shading Accent 3" w:semiHidden="0" w:uiPriority="71" w:unhideWhenUsed="0"/><w:lsdException w:name="Colorful List Accent 3" w:semiHidden="0" w:uiPriority="72" w:unhideWhenUsed="0"/><w:lsdException w:name="Colorful Grid Accent 3" w:semiHidden="0" w:uiPriority="73" w:unhideWhenUsed="0"/><w:lsdException w:name="Light Shading Accent 4" w:semiHidden="0" w:uiPriority="60" w:unhideWhenUsed="0"/><w:lsdException w:name="Light List Accent 4" w:semiHidden="0" w:uiPriority="61" w:unhideWhenUsed="0"/><w:lsdException w:name="Light Grid Accent 4" w:semiHidden="0" w:uiPriority="62" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Shading 1 Accent 4" w:semiHidden="0" w:uiPriority="63" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Shading 2 Accent 4" w:semiHidden="0" w:uiPriority="64" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium List 1 Accent 4" w:semiHidden="0" w:uiPriority="65" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium List 2 Accent 4" w:semiHidden="0" w:uiPriority="66" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Grid 1 Accent 4" w:semiHidden="0" w:uiPriority="67" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Grid 2 Accent 4" w:semiHidden="0" w:uiPriority="68" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Grid 3 Accent 4" w:semiHidden="0" w:uiPriority="69" w:unhideWhenUsed="0"/><w:lsdException w:name="Dark List Accent 4" w:semiHidden="0" w:uiPriority="70" w:unhideWhenUsed="0"/><w:lsdException w:name="Colorful Shading Accent 4" w:semiHidden="0" w:uiPriority="71" w:unhideWhenUsed="0"/><w:lsdException w:name="Colorful List Accent 4" w:semiHidden="0" w:uiPriority="72" w:unhideWhenUsed="0"/><w:lsdException w:name="Colorful Grid Accent 4" w:semiHidden="0" w:uiPriority="73" w:unhideWhenUsed="0"/><w:lsdException w:name="Light Shading Accent 5" w:semiHidden="0" w:uiPriority="60" w:unhideWhenUsed="0"/><w:lsdException w:name="Light List Accent 5" w:semiHidden="0" w:uiPriority="61" w:unhideWhenUsed="0"/><w:lsdException w:name="Light Grid Accent 5" w:semiHidden="0" w:uiPriority="62" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Shading 1 Accent 5" w:semiHidden="0" w:uiPriority="63" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Shading 2 Accent 5" w:semiHidden="0" w:uiPriority="64" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium List 1 Accent 5" w:semiHidden="0" w:uiPriority="65" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium List 2 Accent 5" w:semiHidden="0" w:uiPriority="66" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Grid 1 Accent 5" w:semiHidden="0" w:uiPriority="67" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Grid 2 Accent 5" w:semiHidden="0" w:uiPriority="68" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Grid 3 Accent 5" w:semiHidden="0" w:uiPriority="69" w:unhideWhenUsed="0"/><w:lsdException w:name="Dark List Accent 5" w:semiHidden="0" w:uiPriority="70" w:unhideWhenUsed="0"/><w:lsdException w:name="Colorful Shading Accent 5" w:semiHidden="0" w:uiPriority="71" w:unhideWhenUsed="0"/><w:lsdException w:name="Colorful List Accent 5" w:semiHidden="0" w:uiPriority="72" w:unhideWhenUsed="0"/><w:lsdException w:name="Colorful Grid Accent 5" w:semiHidden="0" w:uiPriority="73" w:unhideWhenUsed="0"/><w:lsdException w:name="Light Shading Accent 6" w:semiHidden="0" w:uiPriority="60" w:unhideWhenUsed="0"/><w:lsdException w:name="Light List Accent 6" w:semiHidden="0" w:uiPriority="61" w:unhideWhenUsed="0"/><w:lsdException w:name="Light Grid Accent 6" w:semiHidden="0" w:uiPriority="62" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Shading 1 Accent 6" w:semiHidden="0" w:uiPriority="63" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Shading 2 Accent 6" w:semiHidden="0" w:uiPriority="64" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium List 1 Accent 6" w:semiHidden="0" w:uiPriority="65" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium List 2 Accent 6" w:semiHidden="0" w:uiPriority="66" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Grid 1 Accent 6" w:semiHidden="0" w:uiPriority="67" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Grid 2 Accent 6" w:semiHidden="0" w:uiPriority="68" w:unhideWhenUsed="0"/><w:lsdException w:name="Medium Grid 3 Accent 6" w:semiHidden="0" w:uiPriority="69" w:unhideWhenUsed="0"/><w:lsdException w:name="Dark List Accent 6" w:semiHidden="0" w:uiPriority="70" w:unhideWhenUsed="0"/><w:lsdException w:name="Colorful Shading Accent 6" w:semiHidden="0" w:uiPriority="71" w:unhideWhenUsed="0"/><w:lsdException w:name="Colorful List Accent 6" w:semiHidden="0" w:uiPriority="72" w:unhideWhenUsed="0"/><w:lsdException w:name="Colorful Grid Accent 6" w:semiHidden="0" w:uiPriority="73" w:unhideWhenUsed="0"/><w:lsdException w:name="Subtle Emphasis" w:semiHidden="0" w:uiPriority="19" w:unhideWhenUsed="0" w:qFormat="1"/><w:lsdException w:name="Intense Emphasis" w:semiHidden="0" w:uiPriority="21" w:unhideWhenUsed="0" w:qFormat="1"/><w:lsdException w:name="Subtle Reference" w:semiHidden="0" w:uiPriority="31" w:unhideWhenUsed="0" w:qFormat="1"/><w:lsdException w:name="Intense Reference" w:semiHidden="0" w:uiPriority="32" w:unhideWhenUsed="0" w:qFormat="1"/><w:lsdException w:name="Book Title" w:semiHidden="0" w:uiPriority="33" w:unhideWhenUsed="0" w:qFormat="1"/><w:lsdException w:name="Bibliography" w:uiPriority="37"/><w:lsdException w:name="TOC Heading" w:uiPriority="39" w:qFormat="1"/></w:latentStyles><w:style w:type="paragraph" w:default="1" w:styleId="a"><w:name w:val="Normal"/><w:qFormat/><w:rsid w:val="008D401F"/><w:pPr><w:widowControl w:val="0"/><w:jc w:val="both"/></w:pPr></w:style><w:style w:type="character" w:default="1" w:styleId="a0"><w:name w:val="Default Paragraph Font"/><w:uiPriority w:val="1"/><w:semiHidden/><w:unhideWhenUsed/></w:style><w:style w:type="table" w:default="1" w:styleId="a1"><w:name w:val="Normal Table"/><w:uiPriority w:val="99"/><w:semiHidden/><w:unhideWhenUsed/><w:qFormat/><w:tblPr><w:tblInd w:w="0" w:type="dxa"/><w:tblCellMar><w:top w:w="0" w:type="dxa"/><w:left w:w="108" w:type="dxa"/><w:bottom w:w="0" w:type="dxa"/><w:right w:w="108" w:type="dxa"/></w:tblCellMar></w:tblPr></w:style><w:style w:type="numbering" w:default="1" w:styleId="a2"><w:name w:val="No List"/><w:uiPriority w:val="99"/><w:semiHidden/><w:unhideWhenUsed/></w:style><w:style w:type="paragraph" w:styleId="a3"><w:name w:val="header"/><w:basedOn w:val="a"/><w:link w:val="Char"/><w:uiPriority w:val="99"/><w:semiHidden/><w:unhideWhenUsed/><w:rsid w:val="008D401F"/><w:pPr><w:pBdr><w:bottom w:val="single" w:sz="6" w:space="1" w:color="auto"/></w:pBdr><w:tabs><w:tab w:val="center" w:pos="4153"/><w:tab w:val="right" w:pos="8306"/></w:tabs><w:snapToGrid w:val="0"/><w:jc w:val="center"/></w:pPr><w:rPr><w:sz w:val="18"/><w:szCs w:val="18"/></w:rPr></w:style><w:style w:type="character" w:customStyle="1" w:styleId="Char"><w:name w:val="页眉 Char"/><w:basedOn w:val="a0"/><w:link w:val="a3"/><w:uiPriority w:val="99"/><w:semiHidden/><w:rsid w:val="008D401F"/><w:rPr><w:sz w:val="18"/><w:szCs w:val="18"/></w:rPr></w:style><w:style w:type="paragraph" w:styleId="a4"><w:name w:val="footer"/><w:basedOn w:val="a"/><w:link w:val="Char0"/><w:uiPriority w:val="99"/><w:semiHidden/><w:unhideWhenUsed/><w:rsid w:val="008D401F"/><w:pPr><w:tabs><w:tab w:val="center" w:pos="4153"/><w:tab w:val="right" w:pos="8306"/></w:tabs><w:snapToGrid w:val="0"/><w:jc w:val="left"/></w:pPr><w:rPr><w:sz w:val="18"/><w:szCs w:val="18"/></w:rPr></w:style><w:style w:type="character" w:customStyle="1" w:styleId="Char0"><w:name w:val="页脚 Char"/><w:basedOn w:val="a0"/><w:link w:val="a4"/><w:uiPriority w:val="99"/><w:semiHidden/><w:rsid w:val="008D401F"/><w:rPr><w:sz w:val="18"/><w:szCs w:val="18"/></w:rPr></w:style><w:style w:type="table" w:styleId="a5"><w:name w:val="Table Grid"/><w:basedOn w:val="a1"/><w:uiPriority w:val="59"/><w:rsid w:val="008D401F"/><w:rPr><w:rFonts w:eastAsia="Times New Roman"/></w:rPr><w:tblPr><w:tblBorders><w:top w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:left w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:bottom w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:right w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:insideH w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/><w:insideV w:val="single" w:sz="4" w:space="0" w:color="000000" w:themeColor="text1"/></w:tblBorders><w:tblCellMar><w:top w:w="0" w:type="dxa"/><w:left w:w="108" w:type="dxa"/><w:bottom w:w="0" w:type="dxa"/><w:right w:w="108" w:type="dxa"/></w:tblCellMar></w:tblPr></w:style><w:style w:type="paragraph" w:styleId="a6"><w:name w:val="Balloon Text"/><w:basedOn w:val="a"/><w:link w:val="Char1"/><w:uiPriority w:val="99"/><w:semiHidden/><w:unhideWhenUsed/><w:rsid w:val="003B578C"/><w:rPr><w:sz w:val="18"/><w:szCs w:val="18"/></w:rPr></w:style><w:style w:type="character" w:customStyle="1" w:styleId="Char1"><w:name w:val="批注框文本 Char"/><w:basedOn w:val="a0"/><w:link w:val="a6"/><w:uiPriority w:val="99"/><w:semiHidden/><w:rsid w:val="003B578C"/><w:rPr><w:sz w:val="18"/><w:szCs w:val="18"/></w:rPr></w:style></w:styles></pkg:xmlData></pkg:part><pkg:part pkg:name="/docProps/core.xml" pkg:contentType="application/vnd.openxmlformats-package.core-properties+xml" pkg:padding="256"><pkg:xmlData><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><dc:creator>PC</dc:creator><cp:lastModifiedBy>PC</cp:lastModifiedBy><cp:revision>2</cp:revision><dcterms:created xsi:type="dcterms:W3CDTF">2019-01-02T06:45:00Z</dcterms:created><dcterms:modified xsi:type="dcterms:W3CDTF">2019-01-02T06:45:00Z</dcterms:modified></cp:coreProperties></pkg:xmlData></pkg:part></pkg:package>